In [ ]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler

In [12]:
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

In [ ]:
import tensorflow
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import InputLayer
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam

In [2]:
ds = pd.read_csv('life_expectancy.csv') # load the dataset

In [3]:
ds.head()

,Country,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,...,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Life expectancy
0,Afghanistan,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,...,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,65.0
1,Afghanistan,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,...,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,59.9
2,Afghanistan,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,...,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,59.9
3,Afghanistan,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,...,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,59.5
4,Afghanistan,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,...,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,59.2

In [4]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2938 entries, 0 to 2937
Data columns (total 22 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   Country                          2938 non-null   object
 1   Year                             2938 non-null   int64
 2   Status                           2938 non-null   object
 3   Adult Mortality                  2938 non-null   float64
 4   infant deaths                    2938 non-null   int64
 5   Alcohol                          2938 non-null   float64
 6   percentage expenditure           2938 non-null   float64
 7   Hepatitis B                      2938 non-null   float64
 8   Measles                          2938 non-null   int64
 9    BMI                             2938 non-null   float64
 10  under-five deaths                2938 non-null   int64
 11  Polio                            2938 non-null   float64
 12  Total expenditure                2938 non-null   float64
 13  Diphtheria                       2938 non-null   float64
 14   HIV/AIDS                        2938 non-null   float64
 15  GDP                              2938 non-null   float64
 16  Population                       2938 non-null   float64
 17   thinness  1-19 years            2938 non-null   float64
 18   thinness 5-9 years              2938 non-null   float64
 19  Income composition of resources  2938 non-null   float64
 20  Schooling                        2938 non-null   float64
 21  Life expectancy                  2938 non-null   float64
dtypes: float64(16), int64(4), object(2)
memory usage: 505.1+ KB

In [5]:
ds['Life expectancy'].describe()

count    2938.000000
mean       69.234717
std         9.509115
min        36.300000
25%        63.200000
50%        72.100000
75%        75.600000
max        89.000000
Name: Life expectancy, dtype: float64

In [3]:
df = ds.drop(['Country'], axis=1)

In [4]:
labels = df['Life expectancy']

In [5]:
features = df.iloc[:,0:-1]
features.head()

,Year,Status,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,2015,Developing,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,2014,Developing,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,2013,Developing,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,2012,Developing,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,2011,Developing,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

### data processing

In [6]:
features = pd.get_dummies(features)
features.head()

,Year,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,BMI,under-five deaths,Polio,...,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling,Status_Developed,Status_Developing
0,2015,263.0,62,0.01,71.279624,65.0,1154,19.1,83,6.0,...,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1,False,True
1,2014,271.0,64,0.01,73.523582,62.0,492,18.6,86,58.0,...,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0,False,True
2,2013,268.0,66,0.01,73.219243,64.0,430,18.1,89,62.0,...,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9,False,True
3,2012,272.0,69,0.01,78.184215,67.0,2787,17.6,93,67.0,...,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8,False,True
4,2011,275.0,71,0.01,7.097109,68.0,3013,17.2,97,68.0,...,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5,False,True

In [8]:
features_train, features_test, labels_train, labels_test = train_test_split(features, labels, 
                test_size=0.2, random_state=23)

In [7]:
num_features = features.select_dtypes(include=['float64', 'int64'])
num_cols = num_features.columns

In [9]:
# standardize
ct = ColumnTransformer([('only_numeric', StandardScaler(), num_cols)], remainder='passthrough')

In [10]:
features_train_scaled = ct.fit_transform(features_train)
features_test_scaled = ct.transform(features_test)

### build the model

In [ ]:
my_model = Sequential()
input = InputLayer(shape=(features.shape[1],)) 
# add the input layer
my_model.add(input) 
# add a hidden layer with 64 neurons
my_model.add(Dense(64, activation='relu')) 
# add an output layer to our model
my_model.add(Dense(1))

In [21]:
print(my_model.summary())

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 64)             │         1,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            65 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,473 (5.75 KB)

 Trainable params: 1,473 (5.75 KB)

 Non-trainable params: 0 (0.00 B)

None

### Initialize optimizer and compile model

In [22]:
opt = Adam(learning_rate=0.01)
my_model.compile(loss='mse',  metrics=['mae'], optimizer=opt)

### Fit and evaluate model

In [23]:
my_model.fit(features_train_scaled, labels_train, epochs=40, 
             batch_size=1, verbose=1)

Epoch 1/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 30:09 770ms/step - loss: 5065.3828 - mae: 71.1715

  19/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 5168.9294 - mae: 71.2655

  54/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4523.1367 - mae: 66.4567

  90/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3918.9014 - mae: 60.6924

 111/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3594.2317 - mae: 56.8911

 128/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3364.7747 - mae: 54.0436

 144/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3175.9716 - mae: 51.6411

 154/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3068.9677 - mae: 50.2513

 166/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2951.3167 - mae: 48.7156

 178/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2843.8782 - mae: 47.3120

 188/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 2760.8080 - mae: 46.2172

 199/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2675.3533 - mae: 45.0745

 210/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2595.5911 - mae: 43.9952

 217/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2547.6239 - mae: 43.3417

 225/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2495.2201 - mae: 42.6245

 236/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2427.0966 - mae: 41.6883

 246/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2368.7106 - mae: 40.8795

 258/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2302.8665 - mae: 39.9659

 274/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2221.3043 - mae: 38.8256

 291/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 2141.6412 - mae: 37.7066

 306/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2076.8172 - mae: 36.7912

 326/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1997.5957 - mae: 35.6667

 345/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1928.5360 - mae: 34.6805

 365/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1861.5798 - mae: 33.7181

 383/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1805.7891 - mae: 32.9100

 404/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1745.4884 - mae: 32.0322

 423/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1694.8902 - mae: 31.2953

 441/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 1649.9747 - mae: 30.6368

 460/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1605.5213 - mae: 29.9840

 481/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1559.5057 - mae: 29.3055

 501/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1518.4668 - mae: 28.6989

 523/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1476.1393 - mae: 28.0710

 539/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1447.0511 - mae: 27.6388

 558/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1414.2046 - mae: 27.1500

 578/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1381.4631 - mae: 26.6614

 597/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1351.9300 - mae: 26.2181

 615/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1325.2635 - mae: 25.8159

 634/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1298.4195 - mae: 25.4106

 649/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1278.1090 - mae: 25.1040

 665/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1257.2492 - mae: 24.7888

 684/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 1233.4772 - mae: 24.4286

 704/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1209.5398 - mae: 24.0643

 728/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1182.1717 - mae: 23.6451

 749/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1159.4228 - mae: 23.2950

 771/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1136.7314 - mae: 22.9456

 792/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1116.0994 - mae: 22.6280

 812/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1097.2849 - mae: 22.3380

 830/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1080.9720 - mae: 22.0864

 846/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1066.9336 - mae: 21.8694

 858/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1056.6764 - mae: 21.7104

 876/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1041.7055 - mae: 21.4776

 896/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1025.6443 - mae: 21.2272

 918/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 1008.6179 - mae: 20.9606

 938/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 993.6992 - mae: 20.7265

 960/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 977.8669 - mae: 20.4773

 981/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 963.2831 - mae: 20.2469

1004/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 947.8728 - mae: 20.0025

1023/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 935.5632 - mae: 19.8065

1041/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 924.2378 - mae: 19.6259

1062/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 911.4251 - mae: 19.4215

1081/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 900.1836 - mae: 19.2419

1102/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 888.1232 - mae: 19.0487

1123/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 876.4307 - mae: 18.8610

1145/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 864.5496 - mae: 18.6695

1164/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 854.5827 - mae: 18.5084

1174/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 849.4427 - mae: 18.4252

1185/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 843.8702 - mae: 18.3348

1195/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 838.8767 - mae: 18.2538

1219/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 827.1714 - mae: 18.0636

1236/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 819.1080 - mae: 17.9325

1251/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 812.1763 - mae: 17.8196

1270/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 803.6021 - mae: 17.6803

1292/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 793.9370 - mae: 17.5231

1308/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 787.0724 - mae: 17.4112

1318/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 782.8509 - mae: 17.3423

1328/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 778.6830 - mae: 17.2743

1344/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 772.1227 - mae: 17.1672

1361/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 765.2918 - mae: 17.0556

1382/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 757.0459 - mae: 16.9207

1400/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 750.1398 - mae: 16.8076

1420/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 742.6331 - mae: 16.6844

1436/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 736.7507 - mae: 16.5877

1453/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 730.6168 - mae: 16.4867

1471/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 724.2507 - mae: 16.3818

1495/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 715.9587 - mae: 16.2449

1522/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 706.8970 - mae: 16.0952

1546/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 699.0615 - mae: 15.9657

1569/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 691.7398 - mae: 15.8445

1593/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 684.2900 - mae: 15.7211

1618/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 676.7238 - mae: 15.5956

1642/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 669.6386 - mae: 15.4778

1664/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 663.2974 - mae: 15.3723

1683/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 657.9322 - mae: 15.2828

1706/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 651.5687 - mae: 15.1764

1734/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 644.0150 - mae: 15.0501

1756/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 638.2215 - mae: 14.9531

1778/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 632.5478 - mae: 14.8581

1803/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 626.2401 - mae: 14.7524

1824/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 621.0527 - mae: 14.6654

1842/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 616.6842 - mae: 14.5919

1862/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 611.9130 - mae: 14.5116

1882/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 607.2263 - mae: 14.4327

1898/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 603.5355 - mae: 14.3703

1916/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 599.4441 - mae: 14.3011

1938/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 594.5303 - mae: 14.2180

1963/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 589.0573 - mae: 14.1252

1981/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 585.1868 - mae: 14.0594

2001/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 580.9582 - mae: 13.9875

2024/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 576.1832 - mae: 13.9064

2044/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 572.1047 - mae: 13.8370

2066/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 567.6961 - mae: 13.7621

2085/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 563.9514 - mae: 13.6983

2110/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 559.1104 - mae: 13.6158

2127/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 555.8730 - mae: 13.5606

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 552.3052 - mae: 13.4996

2168/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 548.2409 - mae: 13.4301

2187/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 544.7866 - mae: 13.3710

2208/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 541.0268 - mae: 13.3066

2229/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 537.3271 - mae: 13.2432

2248/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 534.0333 - mae: 13.1869

2268/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 530.6171 - mae: 13.1285

2291/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 526.7510 - mae: 13.0623

2312/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 523.2772 - mae: 13.0028

2335/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 519.5332 - mae: 12.9386

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 141.8072 - mae: 6.4473

Epoch 2/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:01 26ms/step - loss: 65.4322 - mae: 8.0890

  32/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 24.9941 - mae: 3.8154

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0452 - mae: 3.6258

  72/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.4169 - mae: 3.6560

  91/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 23.6656 - mae: 3.6800

 113/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.1545 - mae: 3.7239

 133/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.7375 - mae: 3.7741

 153/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.9428 - mae: 3.7933

 173/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 25.0022 - mae: 3.8024

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.9005 - mae: 3.7967

 211/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.7493 - mae: 3.7860

 228/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.5770 - mae: 3.7731

 244/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 24.3703 - mae: 3.7568

 265/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 24.0854 - mae: 3.7335

 284/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 23.8331 - mae: 3.7120

 304/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 23.5818 - mae: 3.6898

 321/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 23.3723 - mae: 3.6725

 344/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 23.1939 - mae: 3.6573

 367/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 23.0827 - mae: 3.6479

 385/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 23.0068 - mae: 3.6414

 406/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.9083 - mae: 3.6330

 421/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8553 - mae: 3.6290

 438/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8177 - mae: 3.6264

 459/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.7898 - mae: 3.6243

 477/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.7791 - mae: 3.6242

 496/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.7819 - mae: 3.6250

 513/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.7950 - mae: 3.6266

 520/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8026 - mae: 3.6275

 532/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8129 - mae: 3.6288

 556/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8265 - mae: 3.6311

 572/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8462 - mae: 3.6336

 600/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8662 - mae: 3.6369

 632/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8882 - mae: 3.6404

 666/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.9465 - mae: 3.6460

 702/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0402 - mae: 3.6529

 723/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0883 - mae: 3.6561

 742/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.1250 - mae: 3.6583

 762/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 23.1680 - mae: 3.6611

 781/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.2064 - mae: 3.6636

 797/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.2354 - mae: 3.6653

 814/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.2622 - mae: 3.6670

 834/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.2917 - mae: 3.6691

 848/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.3109 - mae: 3.6704

 877/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.3416 - mae: 3.6724

 890/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.3546 - mae: 3.6732

 913/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.3760 - mae: 3.6748

 930/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.3887 - mae: 3.6757

 949/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4022 - mae: 3.6766

 968/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4160 - mae: 3.6777

 984/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4340 - mae: 3.6792

1005/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4592 - mae: 3.6812

1023/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4816 - mae: 3.6829

1038/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.4995 - mae: 3.6841

1058/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.5223 - mae: 3.6857

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.5427 - mae: 3.6871

1092/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.5620 - mae: 3.6882

1110/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.5793 - mae: 3.6891

1129/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.5972 - mae: 3.6901

1147/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.6135 - mae: 3.6910

1169/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.6302 - mae: 3.6919

1191/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 23.6431 - mae: 3.6926

1211/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6530 - mae: 3.6930

1230/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6599 - mae: 3.6932

1247/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6649 - mae: 3.6933

1269/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6741 - mae: 3.6937

1282/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6819 - mae: 3.6941

1292/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6889 - mae: 3.6945

1302/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.6960 - mae: 3.6948

1311/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7038 - mae: 3.6953

1324/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7225 - mae: 3.6961

1334/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7415 - mae: 3.6969

1340/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7549 - mae: 3.6976

1346/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7695 - mae: 3.6983

1352/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7846 - mae: 3.6991

1359/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8029 - mae: 3.7000

1373/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8416 - mae: 3.7019

1381/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8631 - mae: 3.7030

1393/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8953 - mae: 3.7047

1418/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.9610 - mae: 3.7081

1443/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.0229 - mae: 3.7114

1458/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.0586 - mae: 3.7132

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1027 - mae: 3.7155

1494/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1403 - mae: 3.7175

1516/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1858 - mae: 3.7198

1537/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.2568 - mae: 3.7226

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.3479 - mae: 3.7264

1580/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4199 - mae: 3.7294

1598/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4861 - mae: 3.7322

1612/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.5371 - mae: 3.7344

1644/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.6506 - mae: 3.7395

1673/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.7492 - mae: 3.7440

1713/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.8721 - mae: 3.7494

1743/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 24.9554 - mae: 3.7530

1777/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.0438 - mae: 3.7567

1811/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.1497 - mae: 3.7609

1843/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.2556 - mae: 3.7654

1879/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.3716 - mae: 3.7703

1917/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.4824 - mae: 3.7748

1951/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 25.5754 - mae: 3.7787

1995/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.6854 - mae: 3.7830

2027/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.7618 - mae: 3.7861

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.8114 - mae: 3.7882

2074/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.8702 - mae: 3.7906

2093/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9105 - mae: 3.7923

2106/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9369 - mae: 3.7933

2124/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 25.9717 - mae: 3.7947

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.0117 - mae: 3.7962

2164/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.0440 - mae: 3.7975

2186/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.0835 - mae: 3.7991

2205/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1165 - mae: 3.8003

2227/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1541 - mae: 3.8018

2248/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.1887 - mae: 3.8032

2268/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.2209 - mae: 3.8046

2289/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.2534 - mae: 3.8060

2308/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.2812 - mae: 3.8072

2322/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3007 - mae: 3.8080

2340/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.3245 - mae: 3.8090

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 29.2731 - mae: 3.9279

Epoch 3/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 54s 23ms/step - loss: 19.8085 - mae: 4.4507

  34/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.5120 - mae: 3.1507

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.4424 - mae: 3.0953

  74/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.1752 - mae: 3.0349

  95/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 12.7606 - mae: 2.9649

 114/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 12.5423 - mae: 2.9176

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 12.5844 - mae: 2.9048

 156/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 12.8711 - mae: 2.9230

 172/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.0521 - mae: 2.9363

 186/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.2260 - mae: 2.9515

 202/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.4012 - mae: 2.9684

 220/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.5646 - mae: 2.9830

 241/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.7568 - mae: 2.9975

 270/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.9635 - mae: 3.0118

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 14.2417 - mae: 3.0302

 314/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 14.5242 - mae: 3.0513

 334/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.7924 - mae: 3.0733

 356/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0600 - mae: 3.0950

 378/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.3149 - mae: 3.1150

 399/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.5432 - mae: 3.1328

 417/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.7686 - mae: 3.1484

 434/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 16.1582 - mae: 3.1675

 454/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 16.6208 - mae: 3.1918

 475/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 17.0617 - mae: 3.2152

 494/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 17.4211 - mae: 3.2347

 512/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 17.7336 - mae: 3.2518

 533/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 18.0635 - mae: 3.2699

 557/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 18.3927 - mae: 3.2879

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 18.6075 - mae: 3.2995

 598/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 18.8687 - mae: 3.3138

 630/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 19.2109 - mae: 3.3328

 673/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 19.7100 - mae: 3.3595

 706/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.0749 - mae: 3.3805

 742/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.4621 - mae: 3.4042

 760/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.6487 - mae: 3.4162

 784/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.8708 - mae: 3.4300

 820/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.1626 - mae: 3.4486

 844/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.3310 - mae: 3.4596

 861/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.4375 - mae: 3.4665

 882/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.5536 - mae: 3.4739

 901/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.6473 - mae: 3.4798

 921/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.7348 - mae: 3.4852

 942/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.8199 - mae: 3.4907

 962/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.8950 - mae: 3.4957

 980/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.9565 - mae: 3.4998

 998/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.0132 - mae: 3.5036

1018/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.0711 - mae: 3.5073

1038/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.1287 - mae: 3.5111

1056/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.3068 - mae: 3.5166

1074/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.4860 - mae: 3.5224

1091/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.6481 - mae: 3.5277

1113/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.8540 - mae: 3.5345

1131/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.0208 - mae: 3.5404

1151/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.1966 - mae: 3.5467

1173/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.3797 - mae: 3.5533

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.5617 - mae: 3.5600

1219/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.7366 - mae: 3.5664

1242/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 23.9001 - mae: 3.5723

1260/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.0213 - mae: 3.5767

1285/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.1796 - mae: 3.5825

1300/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.2685 - mae: 3.5857

1314/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.3483 - mae: 3.5886

1331/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.4436 - mae: 3.5921

1350/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.5485 - mae: 3.5961

1370/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.6557 - mae: 3.6002

1389/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.7535 - mae: 3.6040

1408/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.8443 - mae: 3.6075

1426/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 24.9244 - mae: 3.6104

1447/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.0123 - mae: 3.6136

1470/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.1082 - mae: 3.6170

1492/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.2093 - mae: 3.6209

1510/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.2977 - mae: 3.6246

1521/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 25.3505 - mae: 3.6268

1536/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.4205 - mae: 3.6297

1552/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.4914 - mae: 3.6327

1571/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.5708 - mae: 3.6359

1592/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.6536 - mae: 3.6394

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.7317 - mae: 3.6426

1635/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.8108 - mae: 3.6459

1657/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.8845 - mae: 3.6489

1675/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 25.9417 - mae: 3.6513

1697/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.0121 - mae: 3.6542

1718/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.0758 - mae: 3.6569

1737/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.1296 - mae: 3.6591

1759/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.1883 - mae: 3.6615

1778/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.2363 - mae: 3.6635

1798/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.2851 - mae: 3.6655

1817/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.3288 - mae: 3.6673

1836/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.3697 - mae: 3.6690

1848/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.3941 - mae: 3.6700

1866/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.4284 - mae: 3.6713

1887/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.4655 - mae: 3.6727

1906/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.4967 - mae: 3.6738

1934/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 26.5389 - mae: 3.6752

1962/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.5782 - mae: 3.6764

1983/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.6064 - mae: 3.6773

2005/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.6344 - mae: 3.6782

2026/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.6586 - mae: 3.6789

2044/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.6777 - mae: 3.6795

2063/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.6962 - mae: 3.6799

2081/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7119 - mae: 3.6802

2100/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7279 - mae: 3.6806

2121/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7444 - mae: 3.6809

2139/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7581 - mae: 3.6812

2167/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7769 - mae: 3.6815

2185/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7880 - mae: 3.6817

2197/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.7947 - mae: 3.6817

2215/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8049 - mae: 3.6818

2235/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8154 - mae: 3.6819

2254/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8243 - mae: 3.6819

2274/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8323 - mae: 3.6819

2299/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8405 - mae: 3.6817

2321/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8466 - mae: 3.6815

2339/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 26.8513 - mae: 3.6814

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 27.3444 - mae: 3.6583

Epoch 4/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 50s 22ms/step - loss: 0.3527 - mae: 0.5939

  31/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.2904 - mae: 2.1744

  49/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0751 - mae: 2.1337

  54/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.1668 - mae: 2.1434

  67/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 7.5952 - mae: 2.1958

  88/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.1093 - mae: 2.2630

 112/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.5701 - mae: 2.3191

 151/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.3115 - mae: 2.4091

 181/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.6008 - mae: 2.4381

 196/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.7599 - mae: 2.4542

 213/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.9232 - mae: 2.4691

 229/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.0224 - mae: 2.4764

 256/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.1501 - mae: 2.4855

 275/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.2989 - mae: 2.4977

 292/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.4833 - mae: 2.5115

 310/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.7201 - mae: 2.5284

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.0361 - mae: 2.5518

 352/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.4102 - mae: 2.5805

 371/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.7484 - mae: 2.6062

 390/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.0657 - mae: 2.6305

 409/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.3680 - mae: 2.6537

 430/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.6617 - mae: 2.6775

 451/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9189 - mae: 2.6983

 476/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 13.1985 - mae: 2.7209

 501/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.4339 - mae: 2.7402

 523/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.6173 - mae: 2.7554

 543/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.7664 - mae: 2.7679

 568/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.9324 - mae: 2.7825

 598/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.1016 - mae: 2.7980

 621/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.2198 - mae: 2.8089

 642/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.3335 - mae: 2.8188

 660/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.4235 - mae: 2.8267

 679/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.5117 - mae: 2.8345

 698/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.5912 - mae: 2.8417

 714/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.6591 - mae: 2.8478

 738/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 14.7544 - mae: 2.8568

 768/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 14.8625 - mae: 2.8673

 785/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 14.9605 - mae: 2.8738

 804/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.1814 - mae: 2.8836

 820/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.4250 - mae: 2.8938

 837/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.6800 - mae: 2.9051

 858/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.9807 - mae: 2.9188

 879/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.2609 - mae: 2.9316

 900/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.5283 - mae: 2.9439

 920/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.7706 - mae: 2.9551

 938/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.9741 - mae: 2.9644

 951/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.1140 - mae: 2.9708

 963/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.2393 - mae: 2.9766

 986/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.4643 - mae: 2.9870

 995/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.5470 - mae: 2.9908

1001/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.6004 - mae: 2.9932

1010/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.6788 - mae: 2.9968

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.7308 - mae: 2.9993

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.8020 - mae: 3.0026

1030/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.8545 - mae: 3.0051

1046/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 17.9914 - mae: 3.0117

1067/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 18.1637 - mae: 3.0201

1101/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 18.4270 - mae: 3.0335

1130/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 18.6357 - mae: 3.0446

1152/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 18.7819 - mae: 3.0524

1170/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 18.8942 - mae: 3.0584

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 19.0439 - mae: 3.0664

1218/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.1611 - mae: 3.0727

1239/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.2662 - mae: 3.0784

1258/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.3558 - mae: 3.0832

1278/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.4437 - mae: 3.0881

1296/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.5176 - mae: 3.0921

1314/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.5865 - mae: 3.0959

1335/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.6611 - mae: 3.1000

1357/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.7334 - mae: 3.1040

1373/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.7832 - mae: 3.1068

1392/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.8392 - mae: 3.1099

1413/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.8974 - mae: 3.1132

1442/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 19.9708 - mae: 3.1174

1467/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.0304 - mae: 3.1208

1481/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.0619 - mae: 3.1227

1496/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.0948 - mae: 3.1246

1514/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.1331 - mae: 3.1269

1533/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.1715 - mae: 3.1292

1546/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.1974 - mae: 3.1307

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.2256 - mae: 3.1324

1578/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 20.2565 - mae: 3.1343

1596/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.2870 - mae: 3.1361

1616/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3181 - mae: 3.1379

1636/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3480 - mae: 3.1397

1656/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.3766 - mae: 3.1413

1689/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.4194 - mae: 3.1439

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.4508 - mae: 3.1458

1734/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.4723 - mae: 3.1471

1751/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.4927 - mae: 3.1483

1770/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5152 - mae: 3.1498

1786/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5336 - mae: 3.1510

1807/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5588 - mae: 3.1526

1831/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.5865 - mae: 3.1543

1851/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6074 - mae: 3.1557

1871/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6265 - mae: 3.1569

1891/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6436 - mae: 3.1580

1918/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6640 - mae: 3.1592

1947/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6840 - mae: 3.1605

1962/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 20.6938 - mae: 3.1611

1979/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7049 - mae: 3.1618

1998/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7167 - mae: 3.1625

2010/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7238 - mae: 3.1630

2022/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7304 - mae: 3.1635

2042/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7399 - mae: 3.1641

2053/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7444 - mae: 3.1644

2066/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7495 - mae: 3.1647

2079/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7540 - mae: 3.1650

2090/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7580 - mae: 3.1653

2116/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7669 - mae: 3.1660

2151/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7762 - mae: 3.1667

2163/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7789 - mae: 3.1669

2185/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7830 - mae: 3.1673

2197/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7850 - mae: 3.1675

2215/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7876 - mae: 3.1677

2234/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7896 - mae: 3.1680

2251/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7911 - mae: 3.1682

2271/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7926 - mae: 3.1684

2289/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7935 - mae: 3.1687

2309/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7939 - mae: 3.1689

2330/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7933 - mae: 3.1690

2349/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 20.7918 - mae: 3.1690

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 20.5559 - mae: 3.1693

Epoch 5/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:10 30ms/step - loss: 1.5671 - mae: 1.2519

  28/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.3680 - mae: 2.4692

  50/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.5692 - mae: 2.6070

  74/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 12.6687 - mae: 2.7572

 106/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.1016 - mae: 2.7687

 119/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.0439 - mae: 2.7562

 134/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.0396 - mae: 2.7506

 154/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.1321 - mae: 2.7579

 169/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.2341 - mae: 2.7688

 185/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.3462 - mae: 2.7824

 204/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.4965 - mae: 2.8005

 220/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.6481 - mae: 2.8144

 239/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.8352 - mae: 2.8300

 260/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.9924 - mae: 2.8421

 284/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 14.1166 - mae: 2.8506

 323/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.2020 - mae: 2.8534

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.2504 - mae: 2.8565

 367/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.2894 - mae: 2.8594

 390/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.3215 - mae: 2.8616

 410/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.3609 - mae: 2.8649

 431/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.3836 - mae: 2.8666

 452/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.4173 - mae: 2.8682

 472/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.4480 - mae: 2.8696

 491/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.4862 - mae: 2.8721

 510/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.5482 - mae: 2.8770

 528/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.6409 - mae: 2.8845

 546/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.7333 - mae: 2.8925

 571/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.8603 - mae: 2.9033

 588/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.9329 - mae: 2.9092

 604/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0002 - mae: 2.9145

 621/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0724 - mae: 2.9200

 639/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.1477 - mae: 2.9258

 658/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2297 - mae: 2.9322

 682/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.3291 - mae: 2.9404

 703/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.4043 - mae: 2.9467

 719/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4534 - mae: 2.9507

 734/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.4961 - mae: 2.9542

 750/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.5386 - mae: 2.9578

 771/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.5897 - mae: 2.9622

 788/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.6273 - mae: 2.9654

 808/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.6654 - mae: 2.9684

 831/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.7038 - mae: 2.9715

 855/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.7395 - mae: 2.9745

 873/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.7661 - mae: 2.9769

 887/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.7862 - mae: 2.9789

 904/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8109 - mae: 2.9814

 921/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8342 - mae: 2.9838

 937/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8531 - mae: 2.9858

 956/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8705 - mae: 2.9877

 973/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8811 - mae: 2.9888

 993/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8891 - mae: 2.9896

1014/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8941 - mae: 2.9901

1033/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8955 - mae: 2.9903

1057/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8937 - mae: 2.9902

1079/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8901 - mae: 2.9900

1099/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8850 - mae: 2.9896

1123/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8774 - mae: 2.9892

1155/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 15.8754 - mae: 2.9891

1187/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 15.8766 - mae: 2.9889

1210/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 15.9133 - mae: 2.9898

1244/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.9774 - mae: 2.9921

1287/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.0539 - mae: 2.9949

1323/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.1144 - mae: 2.9970

1360/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.1895 - mae: 2.9995

1400/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.2864 - mae: 3.0025

1427/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.3494 - mae: 3.0046

1448/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.3984 - mae: 3.0063

1466/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.4388 - mae: 3.0077

1485/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.4791 - mae: 3.0092

1512/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.5335 - mae: 3.0111

1548/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.6009 - mae: 3.0135

1566/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.6335 - mae: 3.0147

1586/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.6684 - mae: 3.0160

1604/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.6981 - mae: 3.0170

1621/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.7243 - mae: 3.0179

1637/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.7473 - mae: 3.0186

1658/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.7757 - mae: 3.0194

1675/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.7970 - mae: 3.0200

1694/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.8196 - mae: 3.0205

1712/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.8410 - mae: 3.0211

1728/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.8599 - mae: 3.0217

1761/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.9014 - mae: 3.0231

1786/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.9358 - mae: 3.0245

1803/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.9594 - mae: 3.0255

1819/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 16.9819 - mae: 3.0264

1833/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.0010 - mae: 3.0273

1855/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.0305 - mae: 3.0286

1874/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.0560 - mae: 3.0297

1892/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.0795 - mae: 3.0309

1912/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.1122 - mae: 3.0325

1930/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 17.1482 - mae: 3.0342

1946/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.1796 - mae: 3.0358

1965/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2156 - mae: 3.0376

1987/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2573 - mae: 3.0396

2005/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.2985 - mae: 3.0415

2022/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.3371 - mae: 3.0433

2040/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.3767 - mae: 3.0452

2056/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.4106 - mae: 3.0468

2084/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.4673 - mae: 3.0495

2119/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.5352 - mae: 3.0527

2158/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.6092 - mae: 3.0562

2177/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.6459 - mae: 3.0580

2196/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.6820 - mae: 3.0598

2212/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7113 - mae: 3.0612

2227/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7379 - mae: 3.0626

2246/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.7710 - mae: 3.0642

2264/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.8015 - mae: 3.0658

2280/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.8287 - mae: 3.0672

2297/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.8577 - mae: 3.0687

2312/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.8833 - mae: 3.0701

2329/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 17.9113 - mae: 3.0716

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 21.5272 - mae: 3.2558

Epoch 6/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:00 26ms/step - loss: 0.0103 - mae: 0.1014

  18/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 2.9673 - mae: 1.1684

  34/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 4.5635 - mae: 1.4831

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.1412 - mae: 1.7622

  66/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.5926 - mae: 1.8548

  86/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.9833 - mae: 1.9443

 130/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.1834 - mae: 2.0940

 156/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.9331 - mae: 2.1772

 173/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.3329 - mae: 2.2238

 190/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.7273 - mae: 2.2706

 209/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.1248 - mae: 2.3176

 231/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.9048 - mae: 2.3746

 245/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 11.8175 - mae: 2.4186

 259/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.7062 - mae: 2.4662

 275/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.6056 - mae: 2.5174

 305/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.0009 - mae: 2.6017

 332/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.9638 - mae: 2.6632

 348/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 16.4263 - mae: 2.6947

 361/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 16.7655 - mae: 2.7185

 378/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 17.2857 - mae: 2.7485

 395/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 17.8848 - mae: 2.7824

 411/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 18.4031 - mae: 2.8131

 430/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 18.9923 - mae: 2.8473

 448/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 19.4897 - mae: 2.8763

 465/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 19.9132 - mae: 2.9020

 484/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 20.3407 - mae: 2.9291

 505/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 20.7529 - mae: 2.9562

 522/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 21.1110 - mae: 2.9774

 541/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 21.5414 - mae: 3.0022

 561/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 21.9514 - mae: 3.0271

 579/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.2981 - mae: 3.0490

 613/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 22.8821 - mae: 3.0871

 633/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 23.1775 - mae: 3.1071

 665/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 23.5839 - mae: 3.1356

 697/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.9195 - mae: 3.1605

 715/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 24.0751 - mae: 3.1724

 729/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 24.1809 - mae: 3.1806

 746/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 24.2942 - mae: 3.1895

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 24.4064 - mae: 3.1985

 787/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.5031 - mae: 3.2064

 807/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.5818 - mae: 3.2132

 827/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6446 - mae: 3.2189

 845/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6918 - mae: 3.2234

 865/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7331 - mae: 3.2277

 889/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7696 - mae: 3.2318

 920/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7981 - mae: 3.2360

 935/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.8052 - mae: 3.2376

 952/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.8090 - mae: 3.2392

 967/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.8071 - mae: 3.2401

 983/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.8019 - mae: 3.2409

1001/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7918 - mae: 3.2413

1019/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7788 - mae: 3.2416

1036/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7633 - mae: 3.2417

1054/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7447 - mae: 3.2418

1076/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.7172 - mae: 3.2414

1095/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6893 - mae: 3.2408

1114/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6616 - mae: 3.2401

1136/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6349 - mae: 3.2399

1156/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.6159 - mae: 3.2401

1173/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 24.5986 - mae: 3.2401

1203/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.5665 - mae: 3.2401

1225/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.5399 - mae: 3.2398

1242/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.5158 - mae: 3.2393

1257/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4924 - mae: 3.2387

1264/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4808 - mae: 3.2383

1275/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4622 - mae: 3.2377

1301/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.4171 - mae: 3.2361

1318/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.3866 - mae: 3.2350

1344/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.3378 - mae: 3.2331

1377/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.2736 - mae: 3.2305

1410/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.2113 - mae: 3.2282

1425/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1821 - mae: 3.2271

1435/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1620 - mae: 3.2263

1442/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1479 - mae: 3.2257

1449/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1338 - mae: 3.2251

1460/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.1112 - mae: 3.2242

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.0764 - mae: 3.2228

1504/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 24.0196 - mae: 3.2205

1532/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.9593 - mae: 3.2180

1539/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.9441 - mae: 3.2174

1548/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.9244 - mae: 3.2165

1568/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8801 - mae: 3.2146

1580/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8535 - mae: 3.2135

1591/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8292 - mae: 3.2125

1598/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.8138 - mae: 3.2118

1607/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 23.7938 - mae: 3.2110

1624/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.7558 - mae: 3.2093

1642/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.7151 - mae: 3.2076

1660/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.6738 - mae: 3.2057

1678/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.6322 - mae: 3.2038

1697/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.5879 - mae: 3.2017

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.5456 - mae: 3.1997

1734/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.5017 - mae: 3.1977

1756/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.4521 - mae: 3.1955

1773/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.4143 - mae: 3.1938

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.3787 - mae: 3.1922

1810/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.3335 - mae: 3.1903

1830/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.2905 - mae: 3.1884

1850/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.2486 - mae: 3.1866

1870/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.2079 - mae: 3.1850

1891/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.1665 - mae: 3.1834

1912/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.1248 - mae: 3.1817

1948/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.0526 - mae: 3.1788

1972/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 23.0043 - mae: 3.1768

1988/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9722 - mae: 3.1755

2005/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9378 - mae: 3.1741

2020/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.9075 - mae: 3.1728

2038/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8709 - mae: 3.1712

2056/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.8346 - mae: 3.1697

2077/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.7930 - mae: 3.1679

2094/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.7599 - mae: 3.1665

2113/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.7228 - mae: 3.1649

2135/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6801 - mae: 3.1631

2153/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6454 - mae: 3.1617

2171/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.6107 - mae: 3.1602

2193/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.5685 - mae: 3.1584

2229/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4995 - mae: 3.1555

2247/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4649 - mae: 3.1541

2263/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.4342 - mae: 3.1528

2282/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3980 - mae: 3.1513

2304/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3561 - mae: 3.1495

2333/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 22.3008 - mae: 3.1471

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 18.0246 - mae: 2.9681

Epoch 7/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:02 27ms/step - loss: 12.5511 - mae: 3.5427

  35/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.3673 - mae: 2.4434

  52/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.6949 - mae: 2.3615

  69/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.3831 - mae: 2.3369

  83/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.3327 - mae: 2.3433

  90/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.2721 - mae: 2.3424

 101/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.2854 - mae: 2.3494

 122/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.5321 - mae: 2.3821

 156/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.7036 - mae: 2.3962

 176/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8710 - mae: 2.4115

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.9844 - mae: 2.4215

 215/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.0530 - mae: 2.4276

 239/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1004 - mae: 2.4336

 261/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1667 - mae: 2.4410

 275/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.2206 - mae: 2.4465

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.2730 - mae: 2.4528

 312/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3051 - mae: 2.4576

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3293 - mae: 2.4608

 343/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3442 - mae: 2.4633

 358/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3535 - mae: 2.4656

 367/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3560 - mae: 2.4668

 377/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3592 - mae: 2.4682

 386/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3656 - mae: 2.4700

 395/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3736 - mae: 2.4721

 403/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3785 - mae: 2.4736

 410/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3807 - mae: 2.4745

 416/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3816 - mae: 2.4752

 427/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3820 - mae: 2.4765

 436/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3826 - mae: 2.4776

 444/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3815 - mae: 2.4783

 452/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3787 - mae: 2.4788

 475/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3788 - mae: 2.4812

 500/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.4370 - mae: 2.4889

 514/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.4819 - mae: 2.4947

 529/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.5338 - mae: 2.5012

 560/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6371 - mae: 2.5145

 593/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7432 - mae: 2.5286

 615/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.8202 - mae: 2.5381

 636/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.8892 - mae: 2.5466

 652/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.9368 - mae: 2.5527

 668/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.9792 - mae: 2.5582

 687/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.0261 - mae: 2.5638

 704/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.0727 - mae: 2.5689

 720/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.1121 - mae: 2.5733

 738/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.1551 - mae: 2.5780

 758/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.1995 - mae: 2.5830

 778/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.2377 - mae: 2.5874

 796/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.2682 - mae: 2.5910

 815/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.3016 - mae: 2.5948

 834/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.3331 - mae: 2.5983

 855/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.3698 - mae: 2.6025

 875/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.4073 - mae: 2.6067

 896/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.4441 - mae: 2.6109

 912/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.4756 - mae: 2.6145

 931/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.5137 - mae: 2.6187

 974/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.5841 - mae: 2.6268

1009/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.6312 - mae: 2.6322

1026/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.6540 - mae: 2.6347

1044/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.6796 - mae: 2.6372

1067/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.7110 - mae: 2.6403

1088/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.7388 - mae: 2.6432

1108/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.7644 - mae: 2.6461

1127/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.7904 - mae: 2.6490

1146/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.8169 - mae: 2.6519

1164/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.8432 - mae: 2.6547

1182/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.8673 - mae: 2.6573

1201/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.8911 - mae: 2.6599

1219/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.9130 - mae: 2.6623

1246/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.9467 - mae: 2.6659

1272/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.9786 - mae: 2.6695

1302/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.0131 - mae: 2.6737

1318/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.0308 - mae: 2.6758

1338/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.0521 - mae: 2.6785

1359/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.0742 - mae: 2.6812

1388/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.1044 - mae: 2.6850

1430/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.1503 - mae: 2.6907

1457/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.1775 - mae: 2.6942

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.1961 - mae: 2.6966

1495/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2124 - mae: 2.6987

1514/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2294 - mae: 2.7009

1533/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2457 - mae: 2.7030

1552/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2602 - mae: 2.7048

1572/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2738 - mae: 2.7066

1592/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.2859 - mae: 2.7082

1610/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.2959 - mae: 2.7095

1629/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3068 - mae: 2.7110

1651/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3196 - mae: 2.7127

1671/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3310 - mae: 2.7142

1687/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3407 - mae: 2.7154

1705/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3512 - mae: 2.7168

1730/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3677 - mae: 2.7188

1771/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4003 - mae: 2.7225

1794/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4174 - mae: 2.7245

1818/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4342 - mae: 2.7264

1838/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4474 - mae: 2.7279

1864/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4663 - mae: 2.7299

1891/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4850 - mae: 2.7319

1905/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.4948 - mae: 2.7329

1920/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.5051 - mae: 2.7340

1936/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.5152 - mae: 2.7351

1953/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.5257 - mae: 2.7362

1969/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.5353 - mae: 2.7372

1988/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5462 - mae: 2.7382

2005/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5551 - mae: 2.7391

2022/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5639 - mae: 2.7400

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5763 - mae: 2.7412

2085/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.5923 - mae: 2.7429

2118/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6052 - mae: 2.7442

2134/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6117 - mae: 2.7449

2153/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6207 - mae: 2.7458

2170/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6285 - mae: 2.7466

2191/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6380 - mae: 2.7476

2211/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6465 - mae: 2.7486

2228/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6534 - mae: 2.7493

2246/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6616 - mae: 2.7502

2264/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6694 - mae: 2.7510

2284/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6775 - mae: 2.7519

2302/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6842 - mae: 2.7526

2323/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6917 - mae: 2.7535

2342/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.6982 - mae: 2.7542

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 14.5977 - mae: 2.8534

Epoch 8/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 58s 25ms/step - loss: 38.4837 - mae: 6.2035

  30/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 18.5688 - mae: 2.9476

  57/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 17.0459 - mae: 2.8730

  85/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.7933 - mae: 2.8059

 108/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0523 - mae: 2.7585

 125/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.9925 - mae: 2.7628

 139/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.9260 - mae: 2.7615

 152/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 14.7981 - mae: 2.7518

 167/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 14.6631 - mae: 2.7429

 184/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 14.5846 - mae: 2.7402

 205/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 14.4363 - mae: 2.7283

 225/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 14.3275 - mae: 2.7165

 247/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 14.2243 - mae: 2.7068

 269/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 14.1069 - mae: 2.6976

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.9919 - mae: 2.6882

 313/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.9116 - mae: 2.6809

 346/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.7917 - mae: 2.6706

 381/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.6581 - mae: 2.6582

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.6346 - mae: 2.6560

 414/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.6133 - mae: 2.6546

 433/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.5803 - mae: 2.6519

 454/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.5455 - mae: 2.6492

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.5081 - mae: 2.6464

 493/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.4636 - mae: 2.6432

 511/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.4278 - mae: 2.6408

 531/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.3927 - mae: 2.6390

 549/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.3592 - mae: 2.6370

 567/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.3356 - mae: 2.6358

 585/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.3190 - mae: 2.6353

 606/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.2982 - mae: 2.6347

 626/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.2708 - mae: 2.6332

 648/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.2350 - mae: 2.6309

 675/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.1884 - mae: 2.6280

 708/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.1374 - mae: 2.6248

 737/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.0944 - mae: 2.6221

 757/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.0608 - mae: 2.6199

 770/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.0412 - mae: 2.6187

 787/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.0155 - mae: 2.6173

 805/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9880 - mae: 2.6157

 822/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9637 - mae: 2.6144

 839/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9386 - mae: 2.6128

 856/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9218 - mae: 2.6116

 879/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9127 - mae: 2.6109

 900/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9176 - mae: 2.6111

 920/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9207 - mae: 2.6110

 947/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9204 - mae: 2.6106

 967/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9189 - mae: 2.6103

 987/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9203 - mae: 2.6106

1005/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9219 - mae: 2.6109

1027/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9254 - mae: 2.6116

1046/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9291 - mae: 2.6125

1083/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9379 - mae: 2.6142

1124/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9467 - mae: 2.6159

1160/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9539 - mae: 2.6173

1181/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9623 - mae: 2.6185

1191/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9660 - mae: 2.6190

1211/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9722 - mae: 2.6199

1230/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9770 - mae: 2.6206

1248/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9822 - mae: 2.6215

1269/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9881 - mae: 2.6224

1290/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9926 - mae: 2.6232

1308/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.9969 - mae: 2.6240

1325/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0017 - mae: 2.6247

1344/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0076 - mae: 2.6256

1360/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0142 - mae: 2.6264

1377/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0207 - mae: 2.6273

1393/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0269 - mae: 2.6281

1413/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0351 - mae: 2.6292

1452/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0535 - mae: 2.6317

1482/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0668 - mae: 2.6335

1498/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.0728 - mae: 2.6344

1524/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0818 - mae: 2.6358

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0981 - mae: 2.6381

1592/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1213 - mae: 2.6404

1615/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1373 - mae: 2.6420

1635/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1509 - mae: 2.6433

1651/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1624 - mae: 2.6445

1671/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1760 - mae: 2.6458

1687/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1860 - mae: 2.6468

1704/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1967 - mae: 2.6479

1721/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2085 - mae: 2.6490

1739/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2208 - mae: 2.6503

1757/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2323 - mae: 2.6514

1775/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2426 - mae: 2.6524

1797/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2536 - mae: 2.6534

1818/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2633 - mae: 2.6544

1837/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2722 - mae: 2.6552

1862/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2829 - mae: 2.6562

1910/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.3019 - mae: 2.6582

1936/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3106 - mae: 2.6591

1951/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3152 - mae: 2.6596

1971/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3211 - mae: 2.6603

1988/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3258 - mae: 2.6609

2018/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3377 - mae: 2.6622

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3557 - mae: 2.6637

2065/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3658 - mae: 2.6645

2083/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3764 - mae: 2.6654

2104/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3888 - mae: 2.6665

2124/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4024 - mae: 2.6677

2140/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4138 - mae: 2.6687

2157/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4272 - mae: 2.6699

2174/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4402 - mae: 2.6711

2194/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4574 - mae: 2.6726

2215/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4774 - mae: 2.6743

2228/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4895 - mae: 2.6754

2236/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4967 - mae: 2.6761

2258/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5161 - mae: 2.6778

2281/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5359 - mae: 2.6795

2316/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5657 - mae: 2.6822

2340/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5855 - mae: 2.6840

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 15.4940 - mae: 2.8583

Epoch 9/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:06 28ms/step - loss: 6.6911 - mae: 2.5867

  20/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 164.6467 - mae: 8.1166

  39/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 142.4240 - mae: 7.8589

  59/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 133.3462 - mae: 7.8228

  76/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 125.5514 - mae: 7.6899

  95/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 118.2507 - mae: 7.5316

 110/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 113.6288 - mae: 7.3981

 127/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 108.7753 - mae: 7.2442

 147/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 103.4516 - mae: 7.0539

 166/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 98.8194 - mae: 6.8727

 186/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 94.3781 - mae: 6.6896

 200/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 91.4872 - mae: 6.5636

 216/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 88.4215 - mae: 6.4292

 235/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 85.0556 - mae: 6.2767

 254/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 81.9984 - mae: 6.1361

 272/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 79.3766 - mae: 6.0165

 290/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 76.9488 - mae: 5.9041

 299/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 75.7975 - mae: 5.8498

 308/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 74.6950 - mae: 5.7981

 318/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 73.5128 - mae: 5.7420

 326/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 72.5972 - mae: 5.6981

 334/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 71.7070 - mae: 5.6550

 341/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 70.9475 - mae: 5.6178

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 70.3141 - mae: 5.5869

 355/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 69.4935 - mae: 5.5470

 370/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 4ms/step - loss: 68.0175 - mae: 5.4750

 403/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 65.0388 - mae: 5.3282

 430/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 62.8532 - mae: 5.2197

 444/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 61.8097 - mae: 5.1684

 464/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 60.3998 - mae: 5.0994

 488/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 58.8300 - mae: 5.0229

 523/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 56.7355 - mae: 4.9205

 554/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 55.0341 - mae: 4.8357

 568/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 54.3068 - mae: 4.7989

 583/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 53.5610 - mae: 4.7609

 599/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 52.8108 - mae: 4.7225

 613/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 52.1786 - mae: 4.6899

 628/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 51.5252 - mae: 4.6563

 641/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 50.9772 - mae: 4.6282

 655/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 50.4042 - mae: 4.5986

 670/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 49.8109 - mae: 4.5681

 687/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 49.1624 - mae: 4.5348

 706/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 48.4635 - mae: 4.4987

 723/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 47.8617 - mae: 4.4675

 736/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 47.4168 - mae: 4.4444

 752/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 46.8843 - mae: 4.4169

 764/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 46.4943 - mae: 4.3965

 776/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 46.1134 - mae: 4.3767

 795/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 45.5264 - mae: 4.3458

 821/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 44.7544 - mae: 4.3048

 851/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 43.9058 - mae: 4.2596

 869/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 43.4191 - mae: 4.2338

 886/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 42.9739 - mae: 4.2103

 917/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 42.1922 - mae: 4.1686

 950/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 41.4080 - mae: 4.1266

 977/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 40.8049 - mae: 4.0947

 993/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 40.4622 - mae: 4.0766

1003/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 40.2527 - mae: 4.0656

1015/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 40.0051 - mae: 4.0525

1025/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 39.8027 - mae: 4.0419

1034/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 39.6231 - mae: 4.0324

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 39.4463 - mae: 4.0230

1054/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 39.2350 - mae: 4.0118

1064/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 39.0476 - mae: 4.0019

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 38.8445 - mae: 3.9913

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 38.6817 - mae: 3.9827

1097/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 38.4517 - mae: 3.9708

1114/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 38.1587 - mae: 3.9556

1135/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 37.8048 - mae: 3.9371

1182/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 37.0479 - mae: 3.8976

1220/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 36.4731 - mae: 3.8676

1250/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 36.0367 - mae: 3.8447

1273/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 35.7122 - mae: 3.8277

1295/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 35.4114 - mae: 3.8120

1314/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 35.1576 - mae: 3.7987

1334/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 34.8970 - mae: 3.7850

1357/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 34.6049 - mae: 3.7698

1379/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 34.3330 - mae: 3.7555

1395/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 34.1388 - mae: 3.7453

1406/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 34.0071 - mae: 3.7384

1415/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 33.9002 - mae: 3.7327

1423/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 33.8060 - mae: 3.7277

1438/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 33.6317 - mae: 3.7185

1458/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 33.4031 - mae: 3.7063

1478/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 33.1801 - mae: 3.6944

1500/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 32.9408 - mae: 3.6816

1535/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 32.5711 - mae: 3.6619

1570/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 32.2122 - mae: 3.6426

1588/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 32.0341 - mae: 3.6331

1610/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 31.8218 - mae: 3.6217

1646/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31.4843 - mae: 3.6037

1678/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31.1941 - mae: 3.5881

1698/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 31.0172 - mae: 3.5787

1717/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.8525 - mae: 3.5699

1736/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.6911 - mae: 3.5613

1749/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.5820 - mae: 3.5554

1759/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.4990 - mae: 3.5510

1769/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.4167 - mae: 3.5466

1780/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.3269 - mae: 3.5418

1790/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.2462 - mae: 3.5375

1799/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.1742 - mae: 3.5337

1809/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.0948 - mae: 3.5294

1821/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 30.0002 - mae: 3.5243

1838/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.8676 - mae: 3.5172

1861/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.6908 - mae: 3.5076

1897/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.4207 - mae: 3.4930

1922/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.2380 - mae: 3.4830

1945/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 29.0737 - mae: 3.4741

1968/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28.9123 - mae: 3.4653

1988/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 28.7744 - mae: 3.4578

2000/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.6925 - mae: 3.4534

2019/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.5642 - mae: 3.4464

2042/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.4113 - mae: 3.4380

2074/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.2033 - mae: 3.4266

2099/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 28.0438 - mae: 3.4179

2114/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9499 - mae: 3.4127

2120/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.9125 - mae: 3.4107

2130/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.8507 - mae: 3.4073

2148/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.7420 - mae: 3.4013

2161/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6652 - mae: 3.3972

2172/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.6013 - mae: 3.3937

2182/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5437 - mae: 3.3906

2189/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.5038 - mae: 3.3885

2200/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.4415 - mae: 3.3851

2215/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.3576 - mae: 3.3806

2233/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.2581 - mae: 3.3753

2249/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 27.1707 - mae: 3.3706

2286/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.9741 - mae: 3.3601

2324/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.7786 - mae: 3.3498

2349/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 26.6528 - mae: 3.3432

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 14.9263 - mae: 2.7254

Epoch 10/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:11 31ms/step - loss: 1.3892 - mae: 1.1786

  24/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 4.3160 - mae: 1.7382

  43/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 4.8194 - mae: 1.7870

  62/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 5.4083 - mae: 1.8366

  83/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 5.8976 - mae: 1.8895

 105/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 6.4243 - mae: 1.9546

 127/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 6.8225 - mae: 2.0060

 149/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.2479 - mae: 2.0582

 165/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.4762 - mae: 2.0850

 177/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.6836 - mae: 2.1059

 186/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.8275 - mae: 2.1208

 196/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.9755 - mae: 2.1367

 205/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.0995 - mae: 2.1502

 220/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.2794 - mae: 2.1706

 236/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.4376 - mae: 2.1900

 272/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.7043 - mae: 2.2225

 298/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.8338 - mae: 2.2380

 318/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.9001 - mae: 2.2459

 330/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.9296 - mae: 2.2494

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.9648 - mae: 2.2543

 364/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.9976 - mae: 2.2591

 391/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.0896 - mae: 2.2685

 423/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3981 - mae: 2.2884

 455/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.8795 - mae: 2.3135

 482/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.2723 - mae: 2.3347

 505/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.5992 - mae: 2.3532

 519/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.7916 - mae: 2.3647

 530/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9352 - mae: 2.3735

 538/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.0330 - mae: 2.3795

 548/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.1484 - mae: 2.3866

 567/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.3497 - mae: 2.3990

 581/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.4827 - mae: 2.4073

 588/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.5448 - mae: 2.4112

 595/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6043 - mae: 2.4149

 605/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6854 - mae: 2.4200

 616/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7741 - mae: 2.4256

 625/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.8478 - mae: 2.4302

 642/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.9802 - mae: 2.4389

 680/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.2387 - mae: 2.4565

 710/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.4000 - mae: 2.4671

 744/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.5571 - mae: 2.4776

 758/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.6151 - mae: 2.4815

 775/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.6804 - mae: 2.4860

 788/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.7288 - mae: 2.4894

 802/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.7781 - mae: 2.4930

 819/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.8317 - mae: 2.4969

 843/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.8986 - mae: 2.5018

 858/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9355 - mae: 2.5046

 871/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9645 - mae: 2.5068

 888/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9980 - mae: 2.5093

 906/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 13.0293 - mae: 2.5117

 926/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 13.0597 - mae: 2.5141

 947/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.0897 - mae: 2.5166

 966/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.1236 - mae: 2.5191

 987/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.1626 - mae: 2.5221

1008/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.1984 - mae: 2.5250

1030/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.2342 - mae: 2.5281

1050/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.2663 - mae: 2.5308

1070/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.2983 - mae: 2.5336

1091/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.3307 - mae: 2.5365

1107/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.3556 - mae: 2.5387

1124/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.3808 - mae: 2.5410

1134/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.3950 - mae: 2.5424

1141/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4048 - mae: 2.5434

1150/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4170 - mae: 2.5446

1170/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4423 - mae: 2.5471

1182/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4566 - mae: 2.5486

1198/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4757 - mae: 2.5506

1217/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.4979 - mae: 2.5529

1228/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.5101 - mae: 2.5541

1240/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.5228 - mae: 2.5554

1255/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.5372 - mae: 2.5569

1276/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.5563 - mae: 2.5590

1299/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.5838 - mae: 2.5616

1328/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6181 - mae: 2.5651

1369/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6592 - mae: 2.5694

1397/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6821 - mae: 2.5720

1411/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6921 - mae: 2.5731

1432/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7143 - mae: 2.5751

1450/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7389 - mae: 2.5771

1468/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7638 - mae: 2.5792

1488/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7900 - mae: 2.5815

1505/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8110 - mae: 2.5833

1524/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8349 - mae: 2.5854

1545/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8624 - mae: 2.5877

1565/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8886 - mae: 2.5899

1583/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.9111 - mae: 2.5919

1601/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.9321 - mae: 2.5937

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.9454 - mae: 2.5949

1621/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.9543 - mae: 2.5957

1637/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.9713 - mae: 2.5972

1661/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.9946 - mae: 2.5993

1682/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.0137 - mae: 2.6011

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.0398 - mae: 2.6036

1749/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.0647 - mae: 2.6059

1783/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.0853 - mae: 2.6080

1829/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1077 - mae: 2.6104

1863/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1223 - mae: 2.6120

1884/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1302 - mae: 2.6130

1906/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1375 - mae: 2.6139

1926/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1430 - mae: 2.6146

1943/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1487 - mae: 2.6153

1962/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 14.1567 - mae: 2.6162

1981/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1650 - mae: 2.6171

2002/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1735 - mae: 2.6180

2032/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1837 - mae: 2.6193

2070/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1939 - mae: 2.6206

2087/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.1973 - mae: 2.6210

2106/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2005 - mae: 2.6215

2127/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2036 - mae: 2.6220

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2056 - mae: 2.6223

2165/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2069 - mae: 2.6226

2186/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2074 - mae: 2.6228

2205/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2077 - mae: 2.6230

2222/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2082 - mae: 2.6232

2247/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2088 - mae: 2.6235

2290/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2086 - mae: 2.6240

2327/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2082 - mae: 2.6244

2341/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 14.2097 - mae: 2.6246

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 14.5821 - mae: 2.6715

Epoch 11/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:25 37ms/step - loss: 0.3108 - mae: 0.5575

  35/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 30.5555 - mae: 3.7952

  55/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 31.2315 - mae: 3.9527

  71/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 30.0718 - mae: 3.9195

  89/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 28.4125 - mae: 3.8216

 112/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 26.4906 - mae: 3.6871

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 25.2685 - mae: 3.5981

 151/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 24.3828 - mae: 3.5344

 173/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 23.4885 - mae: 3.4718

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 22.8051 - mae: 3.4230

 215/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 22.2737 - mae: 3.3824

 235/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 21.9730 - mae: 3.3517

 257/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 22.0866 - mae: 3.3380

 277/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 22.2390 - mae: 3.3368

 297/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 22.3874 - mae: 3.3385

 329/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 22.7928 - mae: 3.3492

 368/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0928 - mae: 3.3553

 388/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.1822 - mae: 3.3554

 407/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.2188 - mae: 3.3530

 423/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.2236 - mae: 3.3497

 434/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.2177 - mae: 3.3472

 454/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.1937 - mae: 3.3417

 481/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.1312 - mae: 3.3315

 515/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0989 - mae: 3.3225

 538/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0627 - mae: 3.3157

 557/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0442 - mae: 3.3111

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0394 - mae: 3.3081

 595/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.0228 - mae: 3.3047

 619/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 22.9886 - mae: 3.3003

 656/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.9546 - mae: 3.2960

 690/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.9463 - mae: 3.2952

 727/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.9083 - mae: 3.2923

 762/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.8484 - mae: 3.2884

 793/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.7796 - mae: 3.2837

 816/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.7186 - mae: 3.2792

 838/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.6531 - mae: 3.2743

 853/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.6053 - mae: 3.2707

 869/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.5511 - mae: 3.2666

 883/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.5023 - mae: 3.2629

 920/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 22.3689 - mae: 3.2529

 959/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.2214 - mae: 3.2418

 984/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.1235 - mae: 3.2343

 999/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.0632 - mae: 3.2295

1008/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 22.0265 - mae: 3.2267

1030/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.9360 - mae: 3.2197

1058/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.8193 - mae: 3.2108

1097/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.6569 - mae: 3.1983

1128/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.5304 - mae: 3.1887

1165/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.3862 - mae: 3.1777

1179/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.3335 - mae: 3.1738

1199/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.2595 - mae: 3.1683

1216/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.1968 - mae: 3.1637

1235/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.1259 - mae: 3.1585

1257/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 21.0434 - mae: 3.1524

1281/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.9549 - mae: 3.1459

1301/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.8825 - mae: 3.1406

1323/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.8037 - mae: 3.1349

1341/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.7398 - mae: 3.1302

1361/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.6690 - mae: 3.1251

1381/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.5999 - mae: 3.1201

1400/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.5358 - mae: 3.1156

1415/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.4854 - mae: 3.1121

1434/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 20.4227 - mae: 3.1077

1458/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20.3454 - mae: 3.1024

1502/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20.2042 - mae: 3.0925

1544/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 20.0709 - mae: 3.0832

1569/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.9935 - mae: 3.0778

1586/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.9407 - mae: 3.0741

1598/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.9036 - mae: 3.0714

1628/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.8118 - mae: 3.0649

1667/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.6952 - mae: 3.0566

1691/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.6255 - mae: 3.0516

1710/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.5718 - mae: 3.0477

1728/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.5215 - mae: 3.0441

1749/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.4637 - mae: 3.0399

1767/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.4144 - mae: 3.0363

1785/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.3654 - mae: 3.0328

1802/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.3196 - mae: 3.0295

1820/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.2722 - mae: 3.0260

1840/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.2203 - mae: 3.0223

1857/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.1771 - mae: 3.0192

1876/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.1293 - mae: 3.0157

1897/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 19.0773 - mae: 3.0120

1939/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.9749 - mae: 3.0047

1980/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.8771 - mae: 2.9976

2013/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.7999 - mae: 2.9920

2031/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.7580 - mae: 2.9889

2050/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.7137 - mae: 2.9856

2070/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.6672 - mae: 2.9821

2089/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.6230 - mae: 2.9787

2106/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5837 - mae: 2.9757

2126/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5388 - mae: 2.9723

2143/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.5019 - mae: 2.9695

2163/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.4599 - mae: 2.9664

2182/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.4208 - mae: 2.9636

2200/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3846 - mae: 2.9610

2220/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3448 - mae: 2.9581

2236/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.3131 - mae: 2.9558

2254/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.2781 - mae: 2.9533

2272/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.2437 - mae: 2.9509

2292/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.2057 - mae: 2.9482

2315/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.1620 - mae: 2.9450

2337/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 18.1203 - mae: 2.9420

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 13.6733 - mae: 2.6156

Epoch 12/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 50s 21ms/step - loss: 1.9728 - mae: 1.4046

  43/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 10.1198 - mae: 2.4951

  80/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 11.0053 - mae: 2.5438

 101/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.6768 - mae: 2.5751

 128/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3649 - mae: 2.6177

 161/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.6839 - mae: 2.6327

 201/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.6538 - mae: 2.6185

 225/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5667 - mae: 2.6063

 243/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5042 - mae: 2.5979

 261/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.4283 - mae: 2.5886

 278/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3639 - mae: 2.5808

 298/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2868 - mae: 2.5711

 321/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2021 - mae: 2.5593

 339/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2257 - mae: 2.5578

 360/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2644 - mae: 2.5586

 382/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3769 - mae: 2.5663

 402/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.4974 - mae: 2.5760

 423/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.6240 - mae: 2.5866

 441/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.7183 - mae: 2.5948

 457/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 12.7923 - mae: 2.6018

 479/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 12.8864 - mae: 2.6115

 510/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.0038 - mae: 2.6247

 551/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.1304 - mae: 2.6413

 583/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.2052 - mae: 2.6515

 603/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.2481 - mae: 2.6577

 625/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.2859 - mae: 2.6635

 659/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.3298 - mae: 2.6710

 698/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.3603 - mae: 2.6771

 737/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.3822 - mae: 2.6815

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4104 - mae: 2.6858

 787/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4307 - mae: 2.6890

 804/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4444 - mae: 2.6912

 819/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4561 - mae: 2.6933

 837/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4691 - mae: 2.6958

 855/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4799 - mae: 2.6979

 874/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4894 - mae: 2.7000

 892/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4951 - mae: 2.7015

 914/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.5000 - mae: 2.7030

 933/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.5014 - mae: 2.7040

 952/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.5001 - mae: 2.7047

 976/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4968 - mae: 2.7053

 995/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4907 - mae: 2.7054

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4810 - mae: 2.7051

1045/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4659 - mae: 2.7045

1096/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4313 - mae: 2.7028

1132/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.4069 - mae: 2.7016

1157/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.3889 - mae: 2.7008

1176/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.3745 - mae: 2.7001

1199/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.3565 - mae: 2.6992

1233/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.3282 - mae: 2.6977

1262/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.3030 - mae: 2.6963

1279/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2882 - mae: 2.6954

1301/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2732 - mae: 2.6947

1320/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2610 - mae: 2.6941

1340/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2487 - mae: 2.6935

1350/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2424 - mae: 2.6933

1358/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2372 - mae: 2.6930

1366/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2317 - mae: 2.6927

1375/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2256 - mae: 2.6924

1383/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2199 - mae: 2.6921

1388/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2166 - mae: 2.6919

1398/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.2097 - mae: 2.6915

1412/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.1998 - mae: 2.6909

1427/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.1888 - mae: 2.6902

1449/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.1712 - mae: 2.6890

1476/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1488 - mae: 2.6873

1490/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1372 - mae: 2.6864

1498/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1306 - mae: 2.6859

1518/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1136 - mae: 2.6845

1531/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1022 - mae: 2.6836

1543/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0918 - mae: 2.6827

1560/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0769 - mae: 2.6815

1570/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0682 - mae: 2.6809

1596/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0480 - mae: 2.6793

1626/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0454 - mae: 2.6785

1663/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0513 - mae: 2.6785

1689/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0573 - mae: 2.6786

1711/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.0871 - mae: 2.6791

1731/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1145 - mae: 2.6798

1749/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1388 - mae: 2.6804

1762/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1558 - mae: 2.6808

1782/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1807 - mae: 2.6814

1803/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2047 - mae: 2.6818

1824/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2274 - mae: 2.6822

1843/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2468 - mae: 2.6825

1862/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2667 - mae: 2.6828

1881/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2855 - mae: 2.6831

1902/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.3050 - mae: 2.6834

1921/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.3218 - mae: 2.6836

1943/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3407 - mae: 2.6837

1956/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3521 - mae: 2.6839

1967/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3614 - mae: 2.6839

1977/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3696 - mae: 2.6840

1985/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3760 - mae: 2.6840

1995/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3838 - mae: 2.6841

2004/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3906 - mae: 2.6841

2015/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.3989 - mae: 2.6842

2025/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4064 - mae: 2.6843

2034/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4131 - mae: 2.6843

2042/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4189 - mae: 2.6844

2053/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4267 - mae: 2.6844

2079/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4441 - mae: 2.6845

2115/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.4660 - mae: 2.6845

2150/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.4856 - mae: 2.6844

2185/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5070 - mae: 2.6845

2209/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5204 - mae: 2.6845

2235/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5337 - mae: 2.6845

2243/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5376 - mae: 2.6845

2256/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5436 - mae: 2.6844

2288/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5578 - mae: 2.6843

2321/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5711 - mae: 2.6841

2347/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.5803 - mae: 2.6839

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 14.4227 - mae: 2.6641

Epoch 13/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:22 35ms/step - loss: 1.8099 - mae: 1.3453

  15/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.7960 - mae: 2.0207

  30/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 9.1923 - mae: 2.2185

  48/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 8.7050 - mae: 2.2054

  64/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 8.7603 - mae: 2.2400

  85/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.1133 - mae: 2.2756

 100/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 9.6022 - mae: 2.3173

 128/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.1322 - mae: 2.3659

 169/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.4210 - mae: 2.3938

 206/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.5785 - mae: 2.4182

 237/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.6764 - mae: 2.4318

 259/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7270 - mae: 2.4381

 279/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7884 - mae: 2.4449

 298/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8224 - mae: 2.4493

 318/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8514 - mae: 2.4539

 339/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8584 - mae: 2.4560

 360/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8505 - mae: 2.4573

 380/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8348 - mae: 2.4577

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.8169 - mae: 2.4574

 417/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7891 - mae: 2.4562

 440/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7456 - mae: 2.4536

 483/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7478 - mae: 2.4512

 515/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.7623 - mae: 2.4508

 540/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7718 - mae: 2.4512

 558/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7743 - mae: 2.4511

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7757 - mae: 2.4512

 606/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7824 - mae: 2.4506

 628/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7894 - mae: 2.4503

 646/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8024 - mae: 2.4506

 664/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8144 - mae: 2.4509

 683/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8261 - mae: 2.4510

 703/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8380 - mae: 2.4513

 724/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8475 - mae: 2.4513

 745/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8579 - mae: 2.4517

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8680 - mae: 2.4524

 786/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8760 - mae: 2.4529

 809/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8811 - mae: 2.4530

 831/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8871 - mae: 2.4534

 853/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8936 - mae: 2.4541

 874/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8966 - mae: 2.4542

 894/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8968 - mae: 2.4541

 913/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8963 - mae: 2.4538

 933/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9003 - mae: 2.4538

 955/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9057 - mae: 2.4538

 975/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9087 - mae: 2.4538

 997/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9101 - mae: 2.4537

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9097 - mae: 2.4534

1038/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9063 - mae: 2.4529

1064/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8987 - mae: 2.4517

1100/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8875 - mae: 2.4500

1136/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8790 - mae: 2.4488

1167/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8752 - mae: 2.4479

1182/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8726 - mae: 2.4474

1197/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8703 - mae: 2.4469

1217/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8675 - mae: 2.4464

1224/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8667 - mae: 2.4462

1238/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8671 - mae: 2.4460

1275/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8699 - mae: 2.4456

1305/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8687 - mae: 2.4449

1324/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8703 - mae: 2.4446

1344/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8720 - mae: 2.4444

1365/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8732 - mae: 2.4441

1386/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8744 - mae: 2.4438

1407/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8750 - mae: 2.4436

1428/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8752 - mae: 2.4433

1444/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8757 - mae: 2.4432

1462/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8756 - mae: 2.4430

1479/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8759 - mae: 2.4428

1497/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.8850 - mae: 2.4429

1512/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.8932 - mae: 2.4432

1531/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.9044 - mae: 2.4436

1551/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.9217 - mae: 2.4442

1577/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.9422 - mae: 2.4450

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.9682 - mae: 2.4460

1645/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.9888 - mae: 2.4467

1671/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0042 - mae: 2.4472

1685/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0116 - mae: 2.4474

1711/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0237 - mae: 2.4477

1737/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0350 - mae: 2.4480

1758/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0434 - mae: 2.4482

1783/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0528 - mae: 2.4485

1796/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0575 - mae: 2.4486

1804/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0602 - mae: 2.4486

1812/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0628 - mae: 2.4487

1823/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0663 - mae: 2.4487

1839/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0710 - mae: 2.4488

1858/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0764 - mae: 2.4488

1879/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0824 - mae: 2.4489

1892/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0857 - mae: 2.4489

1913/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.0902 - mae: 2.4488

1942/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.0964 - mae: 2.4488

1967/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1025 - mae: 2.4488

1984/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1062 - mae: 2.4488

2002/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1094 - mae: 2.4487

2019/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1134 - mae: 2.4487

2038/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1185 - mae: 2.4488

2057/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1242 - mae: 2.4490

2070/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1279 - mae: 2.4491

2079/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1305 - mae: 2.4492

2088/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1331 - mae: 2.4493

2095/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1350 - mae: 2.4493

2108/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1384 - mae: 2.4494

2142/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1484 - mae: 2.4497

2179/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1581 - mae: 2.4501

2212/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1653 - mae: 2.4502

2236/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1695 - mae: 2.4503

2272/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1748 - mae: 2.4502

2306/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1803 - mae: 2.4502

2329/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.1837 - mae: 2.4502

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 11.4869 - mae: 2.4433

Epoch 14/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 55s 23ms/step - loss: 0.0600 - mae: 0.2449

  25/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.6745 - mae: 2.1603

  43/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 11.1160 - mae: 2.3897

  58/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3816 - mae: 2.4117

  70/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.3984 - mae: 2.4230

  81/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 11.3248 - mae: 2.4224

  92/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 11.1529 - mae: 2.4042

 107/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.9803 - mae: 2.3866

 122/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.9011 - mae: 2.3835

 143/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.8878 - mae: 2.3870

 162/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.8897 - mae: 2.3949

 176/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.8722 - mae: 2.3985

 198/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.8137 - mae: 2.4010

 232/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.6847 - mae: 2.4000

 269/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.7237 - mae: 2.4108

 297/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.7862 - mae: 2.4202

 312/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8172 - mae: 2.4248

 320/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8301 - mae: 2.4267

 328/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8431 - mae: 2.4285

 343/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8577 - mae: 2.4311

 357/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8621 - mae: 2.4328

 368/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8575 - mae: 2.4332

 377/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.8511 - mae: 2.4332

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8407 - mae: 2.4336

 410/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8428 - mae: 2.4346

 431/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8475 - mae: 2.4365

 451/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8461 - mae: 2.4376

 477/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8530 - mae: 2.4405

 508/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8592 - mae: 2.4444

 541/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8475 - mae: 2.4461

 569/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.8268 - mae: 2.4461

 607/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.8091 - mae: 2.4458

 629/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.8180 - mae: 2.4472

 649/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.8502 - mae: 2.4503

 678/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.8924 - mae: 2.4543

 702/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9218 - mae: 2.4568

 720/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9445 - mae: 2.4587

 737/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9641 - mae: 2.4604

 746/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9731 - mae: 2.4612

 760/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 10.9884 - mae: 2.4625

 782/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.0121 - mae: 2.4647

 812/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.0454 - mae: 2.4683

 833/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.0666 - mae: 2.4708

 855/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.0844 - mae: 2.4728

 873/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.0964 - mae: 2.4742

 892/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1061 - mae: 2.4753

 913/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1151 - mae: 2.4762

 934/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1260 - mae: 2.4775

 954/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1390 - mae: 2.4789

 976/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1541 - mae: 2.4805

 996/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1647 - mae: 2.4816

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1733 - mae: 2.4825

1037/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1807 - mae: 2.4833

1061/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1876 - mae: 2.4841

1076/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1917 - mae: 2.4846

1097/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.1977 - mae: 2.4855

1126/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.2075 - mae: 2.4870

1145/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.2132 - mae: 2.4879

1164/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.2208 - mae: 2.4888

1180/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.2283 - mae: 2.4896

1199/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2377 - mae: 2.4907

1218/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2462 - mae: 2.4917

1241/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2551 - mae: 2.4926

1263/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2682 - mae: 2.4939

1280/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2781 - mae: 2.4948

1299/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.2889 - mae: 2.4958

1316/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.3047 - mae: 2.4970

1335/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.3272 - mae: 2.4984

1356/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.3499 - mae: 2.4997

1375/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.3693 - mae: 2.5009

1390/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.3841 - mae: 2.5018

1407/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4000 - mae: 2.5028

1426/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4161 - mae: 2.5038

1449/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4336 - mae: 2.5048

1467/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4464 - mae: 2.5055

1486/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4586 - mae: 2.5062

1509/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4719 - mae: 2.5068

1526/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4806 - mae: 2.5072

1545/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4895 - mae: 2.5076

1564/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.4978 - mae: 2.5079

1583/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.5053 - mae: 2.5082

1602/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5118 - mae: 2.5084

1634/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5221 - mae: 2.5087

1675/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5316 - mae: 2.5087

1708/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5373 - mae: 2.5085

1732/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5438 - mae: 2.5085

1752/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5489 - mae: 2.5085

1786/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5553 - mae: 2.5084

1810/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5584 - mae: 2.5081

1831/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5601 - mae: 2.5079

1849/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5610 - mae: 2.5075

1869/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5616 - mae: 2.5072

1882/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5616 - mae: 2.5069

1897/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5615 - mae: 2.5066

1914/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5612 - mae: 2.5063

1933/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5606 - mae: 2.5058

1953/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.5596 - mae: 2.5054

1969/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5584 - mae: 2.5050

1986/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5568 - mae: 2.5045

2003/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5551 - mae: 2.5040

2021/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5539 - mae: 2.5036

2039/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5528 - mae: 2.5032

2057/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5513 - mae: 2.5028

2075/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5493 - mae: 2.5023

2094/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5477 - mae: 2.5019

2113/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5461 - mae: 2.5014

2132/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5441 - mae: 2.5009

2149/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5424 - mae: 2.5005

2167/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5406 - mae: 2.5001

2184/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5391 - mae: 2.4998

2200/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5378 - mae: 2.4995

2230/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5379 - mae: 2.4991

2273/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5384 - mae: 2.4988

2307/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5389 - mae: 2.4986

2334/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.5391 - mae: 2.4984

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 11.5777 - mae: 2.4889

Epoch 15/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:36 41ms/step - loss: 3.0624 - mae: 1.7500

  38/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 4.8328 - mae: 1.8121

  81/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 5.5044 - mae: 1.8984

 112/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 6.1734 - mae: 1.9811

 134/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4404 - mae: 2.0101

 158/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8381 - mae: 2.0561

 177/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1479 - mae: 2.0926

 196/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4100 - mae: 2.1207

 214/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5928 - mae: 2.1398

 238/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.8170 - mae: 2.1637

 258/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.9404 - mae: 2.1744

 277/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.0247 - mae: 2.1809

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.0915 - mae: 2.1869

 313/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1826 - mae: 2.1965

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.3025 - mae: 2.2089

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.4135 - mae: 2.2214

 365/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.5292 - mae: 2.2348

 378/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.6037 - mae: 2.2434

 395/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.7006 - mae: 2.2551

 416/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.8000 - mae: 2.2670

 442/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.9152 - mae: 2.2812

 477/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.0436 - mae: 2.2974

 511/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.1446 - mae: 2.3106

 533/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.1889 - mae: 2.3162

 554/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.2180 - mae: 2.3199

 594/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2524 - mae: 2.3239

 623/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2618 - mae: 2.3247

 654/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2592 - mae: 2.3240

 673/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2551 - mae: 2.3232

 691/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2516 - mae: 2.3225

 714/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2458 - mae: 2.3218

 734/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2401 - mae: 2.3212

 752/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2350 - mae: 2.3208

 773/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2278 - mae: 2.3200

 791/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2195 - mae: 2.3190

 808/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2138 - mae: 2.3183

 829/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2269 - mae: 2.3184

 850/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2737 - mae: 2.3193

 871/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3195 - mae: 2.3205

 890/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3588 - mae: 2.3217

 908/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3951 - mae: 2.3231

 928/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4329 - mae: 2.3247

 946/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4695 - mae: 2.3266

 966/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5096 - mae: 2.3289

 986/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5485 - mae: 2.3312

1003/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5825 - mae: 2.3334

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6212 - mae: 2.3358

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6594 - mae: 2.3382

1062/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7042 - mae: 2.3410

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7576 - mae: 2.3445

1101/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8009 - mae: 2.3474

1117/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8414 - mae: 2.3501

1134/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8845 - mae: 2.3531

1152/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.9285 - mae: 2.3561

1170/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.9699 - mae: 2.3590

1189/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.0101 - mae: 2.3617

1208/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.0474 - mae: 2.3641

1230/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.0878 - mae: 2.3667

1248/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.1189 - mae: 2.3687

1269/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.1532 - mae: 2.3708

1290/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.1865 - mae: 2.3730

1320/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.2307 - mae: 2.3757

1361/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.2867 - mae: 2.3794

1386/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.3184 - mae: 2.3815

1404/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.3399 - mae: 2.3830

1422/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.3605 - mae: 2.3844

1446/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.3855 - mae: 2.3861

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.4162 - mae: 2.3882

1499/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.4370 - mae: 2.3897

1519/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.4564 - mae: 2.3911

1536/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.4726 - mae: 2.3923

1553/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.4877 - mae: 2.3934

1573/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5050 - mae: 2.3947

1592/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5205 - mae: 2.3959

1610/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5346 - mae: 2.3969

1629/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5495 - mae: 2.3980

1647/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5647 - mae: 2.3991

1669/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5833 - mae: 2.4005

1688/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.5982 - mae: 2.4016

1709/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6135 - mae: 2.4027

1728/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6266 - mae: 2.4037

1743/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6367 - mae: 2.4044

1762/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6510 - mae: 2.4054

1782/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6678 - mae: 2.4065

1800/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.6842 - mae: 2.4077

1819/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7014 - mae: 2.4090

1839/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7188 - mae: 2.4103

1863/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7383 - mae: 2.4117

1884/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7547 - mae: 2.4130

1902/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7679 - mae: 2.4140

1920/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 10.7805 - mae: 2.4150

1938/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.7926 - mae: 2.4160

1952/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8017 - mae: 2.4167

1957/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8049 - mae: 2.4169

1969/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8130 - mae: 2.4176

1994/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8298 - mae: 2.4189

2015/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8445 - mae: 2.4201

2041/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8615 - mae: 2.4215

2077/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.8827 - mae: 2.4232

2109/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9016 - mae: 2.4247

2123/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9102 - mae: 2.4254

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9234 - mae: 2.4265

2185/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9442 - mae: 2.4281

2206/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9548 - mae: 2.4289

2225/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9643 - mae: 2.4296

2243/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9729 - mae: 2.4303

2260/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9807 - mae: 2.4309

2277/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9884 - mae: 2.4315

2296/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 10.9967 - mae: 2.4322

2315/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.0051 - mae: 2.4329

2336/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.0148 - mae: 2.4337

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 12.1776 - mae: 2.5322

Epoch 16/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:02 27ms/step - loss: 2.8316 - mae: 1.6827

  39/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 7.2656 - mae: 2.2726

  60/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8850 - mae: 2.1836

  79/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.8526 - mae: 2.1483

  99/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.9156 - mae: 2.1417

 121/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0159 - mae: 2.1438

 138/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0442 - mae: 2.1431

 153/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.1321 - mae: 2.1457

 168/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.2086 - mae: 2.1480

 185/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.4030 - mae: 2.1573

 203/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.6145 - mae: 2.1706

 223/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.8263 - mae: 2.1855

 244/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.0051 - mae: 2.1986

 279/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1979 - mae: 2.2103

 318/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.3631 - mae: 2.2210

 351/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.4903 - mae: 2.2290

 380/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.5809 - mae: 2.2340

 406/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.6624 - mae: 2.2381

 435/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.7504 - mae: 2.2425

 458/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.8105 - mae: 2.2461

 476/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.8618 - mae: 2.2499

 493/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.9092 - mae: 2.2532

 510/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.9674 - mae: 2.2576

 529/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.0225 - mae: 2.2617

 548/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.0673 - mae: 2.2647

 567/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.1085 - mae: 2.2676

 588/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.1436 - mae: 2.2698

 609/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.1740 - mae: 2.2717

 632/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2051 - mae: 2.2737

 651/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2286 - mae: 2.2752

 669/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2457 - mae: 2.2761

 688/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2601 - mae: 2.2767

 708/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2743 - mae: 2.2774

 728/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2870 - mae: 2.2781

 747/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2963 - mae: 2.2786

 764/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3014 - mae: 2.2787

 785/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3055 - mae: 2.2785

 803/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3074 - mae: 2.2781

 821/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3111 - mae: 2.2779

 842/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3130 - mae: 2.2774

 860/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3137 - mae: 2.2769

 884/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3136 - mae: 2.2763

 915/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3101 - mae: 2.2750

 951/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3004 - mae: 2.2730

 989/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2869 - mae: 2.2705

1023/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2792 - mae: 2.2687

1042/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2757 - mae: 2.2679

1076/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2690 - mae: 2.2665

1105/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2633 - mae: 2.2653

1132/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2609 - mae: 2.2645

1148/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2602 - mae: 2.2642

1167/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2610 - mae: 2.2640

1188/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2611 - mae: 2.2638

1207/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2602 - mae: 2.2635

1226/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2584 - mae: 2.2631

1245/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2568 - mae: 2.2628

1265/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2548 - mae: 2.2624

1287/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2542 - mae: 2.2623

1308/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2542 - mae: 2.2623

1323/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2539 - mae: 2.2623

1343/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2533 - mae: 2.2622

1362/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2548 - mae: 2.2624

1383/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2556 - mae: 2.2625

1401/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2554 - mae: 2.2625

1422/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2543 - mae: 2.2625

1443/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2522 - mae: 2.2623

1456/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2505 - mae: 2.2621

1466/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2490 - mae: 2.2620

1478/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2470 - mae: 2.2617

1493/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2450 - mae: 2.2615

1511/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.2436 - mae: 2.2613

1545/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2411 - mae: 2.2609

1574/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2387 - mae: 2.2605

1608/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2377 - mae: 2.2603

1638/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2430 - mae: 2.2605

1669/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2496 - mae: 2.2609

1689/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2546 - mae: 2.2612

1718/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2609 - mae: 2.2615

1739/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2652 - mae: 2.2618

1759/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2688 - mae: 2.2619

1778/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2723 - mae: 2.2621

1795/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2758 - mae: 2.2624

1809/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2791 - mae: 2.2626

1824/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2822 - mae: 2.2628

1842/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2866 - mae: 2.2631

1853/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2895 - mae: 2.2633

1865/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2928 - mae: 2.2636

1878/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2964 - mae: 2.2638

1896/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3013 - mae: 2.2642

1917/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3073 - mae: 2.2647

1935/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3123 - mae: 2.2650

1953/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3169 - mae: 2.2654

1971/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3213 - mae: 2.2658

1989/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3257 - mae: 2.2661

2004/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3297 - mae: 2.2665

2023/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3349 - mae: 2.2669

2045/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3414 - mae: 2.2675

2066/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3483 - mae: 2.2683

2090/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3556 - mae: 2.2690

2111/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3621 - mae: 2.2697

2135/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3696 - mae: 2.2705

2156/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3759 - mae: 2.2712

2176/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3813 - mae: 2.2718

2197/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3867 - mae: 2.2724

2215/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3911 - mae: 2.2729

2229/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3944 - mae: 2.2733

2260/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4016 - mae: 2.2741

2301/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4104 - mae: 2.2750

2335/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4177 - mae: 2.2758

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 9.9307 - mae: 2.3330

Epoch 17/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:26 37ms/step - loss: 5.1057 - mae: 2.2596

  25/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.5278 - mae: 1.7380

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.8392 - mae: 1.8166

  77/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.7828 - mae: 1.8434

 102/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.8839 - mae: 1.8891

 124/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.9854 - mae: 1.9241

 145/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.1717 - mae: 1.9582

 161/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.3082 - mae: 1.9830

 175/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 6.3978 - mae: 1.9978

 186/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 6.4843 - mae: 2.0100

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 6.5439 - mae: 2.0183

 203/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.6028 - mae: 2.0268

 212/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.6495 - mae: 2.0334

 221/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.6985 - mae: 2.0402

 229/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.7443 - mae: 2.0463

 237/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.7826 - mae: 2.0511

 244/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.8131 - mae: 2.0546

 251/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6.8625 - mae: 2.0592

 262/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 6.9337 - mae: 2.0660

 281/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7.0714 - mae: 2.0796

 309/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.2432 - mae: 2.0964

 323/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.3295 - mae: 2.1041

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 7.3906 - mae: 2.1094

 339/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7.4498 - mae: 2.1148

 349/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7.5237 - mae: 2.1218

 360/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7.5982 - mae: 2.1290

 377/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 7.7030 - mae: 2.1389

 411/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.8933 - mae: 2.1571

 441/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.0165 - mae: 2.1684

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 8.1240 - mae: 2.1777

 499/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.2026 - mae: 2.1844

 529/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.2717 - mae: 2.1897

 552/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.3116 - mae: 2.1921

 566/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.3353 - mae: 2.1935

 600/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.4212 - mae: 2.1990

 619/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.4666 - mae: 2.2021

 638/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.5129 - mae: 2.2052

 656/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.5584 - mae: 2.2086

 673/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.5997 - mae: 2.2120

 691/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.6403 - mae: 2.2154

 710/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.6774 - mae: 2.2185

 731/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7120 - mae: 2.2211

 747/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7336 - mae: 2.2226

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7545 - mae: 2.2240

 779/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7663 - mae: 2.2246

 793/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7777 - mae: 2.2252

 809/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7892 - mae: 2.2258

 823/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.7984 - mae: 2.2264

 831/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8040 - mae: 2.2267

 839/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8093 - mae: 2.2271

 845/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8132 - mae: 2.2274

 854/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8190 - mae: 2.2279

 878/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8313 - mae: 2.2287

 912/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8481 - mae: 2.2301

 952/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8663 - mae: 2.2316

 966/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8739 - mae: 2.2324

 979/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8820 - mae: 2.2331

 996/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.8919 - mae: 2.2340

1027/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.9285 - mae: 2.2363

1056/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.9874 - mae: 2.2399

1086/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.0501 - mae: 2.2440

1104/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.0847 - mae: 2.2463

1135/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1420 - mae: 2.2499

1164/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1895 - mae: 2.2528

1193/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.2322 - mae: 2.2554

1231/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.2817 - mae: 2.2584

1267/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.3214 - mae: 2.2606

1299/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.3548 - mae: 2.2627

1323/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.3828 - mae: 2.2646

1347/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4096 - mae: 2.2664

1355/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4185 - mae: 2.2670

1370/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4346 - mae: 2.2681

1396/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4619 - mae: 2.2699

1407/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4738 - mae: 2.2708

1416/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4838 - mae: 2.2715

1425/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.4942 - mae: 2.2722

1433/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.5033 - mae: 2.2729

1446/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.5176 - mae: 2.2740

1471/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.5435 - mae: 2.2759

1501/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.5731 - mae: 2.2781

1528/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.5999 - mae: 2.2802

1556/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.6267 - mae: 2.2825

1568/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.6380 - mae: 2.2834

1591/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.6606 - mae: 2.2855

1612/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.6809 - mae: 2.2874

1628/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.6956 - mae: 2.2888

1646/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7113 - mae: 2.2902

1659/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7224 - mae: 2.2912

1666/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7283 - mae: 2.2918

1674/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7349 - mae: 2.2924

1687/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7461 - mae: 2.2935

1695/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7529 - mae: 2.2941

1703/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7595 - mae: 2.2948

1711/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7660 - mae: 2.2954

1729/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7805 - mae: 2.2968

1750/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.7979 - mae: 2.2984

1770/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8134 - mae: 2.2999

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8280 - mae: 2.3014

1801/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8370 - mae: 2.3023

1811/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8443 - mae: 2.3030

1828/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8564 - mae: 2.3042

1849/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8706 - mae: 2.3056

1878/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.8894 - mae: 2.3074

1902/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.9040 - mae: 2.3088

1931/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.9210 - mae: 2.3105

1961/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.9384 - mae: 2.3122

1986/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.9534 - mae: 2.3137

1997/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9599 - mae: 2.3144

2014/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9701 - mae: 2.3154

2036/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9827 - mae: 2.3168

2047/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9887 - mae: 2.3174

2063/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.9969 - mae: 2.3182

2084/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0072 - mae: 2.3193

2098/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0138 - mae: 2.3199

2125/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0253 - mae: 2.3211

2147/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0338 - mae: 2.3220

2165/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0402 - mae: 2.3226

2180/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0454 - mae: 2.3231

2195/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0505 - mae: 2.3235

2211/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0557 - mae: 2.3240

2227/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0607 - mae: 2.3245

2235/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0631 - mae: 2.3247

2243/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0654 - mae: 2.3249

2249/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0671 - mae: 2.3250

2267/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0722 - mae: 2.3255

2299/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0804 - mae: 2.3263

2317/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0847 - mae: 2.3267

2333/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0885 - mae: 2.3270

2346/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.0913 - mae: 2.3273

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.6246 - mae: 2.3777

Epoch 18/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:30 39ms/step - loss: 2.5196 - mae: 1.5873

  22/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 3.8184 - mae: 1.7423

  33/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 5.0133 - mae: 1.8735

  41/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 5.8515 - mae: 1.9573

  49/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 6.6140 - mae: 2.0418

  67/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7.4748 - mae: 2.1403

  88/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7.9551 - mae: 2.1871

 102/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.0598 - mae: 2.1924

 116/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.1036 - mae: 2.1934

 123/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.1267 - mae: 2.1950

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.1499 - mae: 2.1969

 153/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.3361 - mae: 2.2067

 163/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.5049 - mae: 2.2166

 184/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 8.8749 - mae: 2.2409

 208/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.1455 - mae: 2.2561

 235/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 9.3435 - mae: 2.2661

 261/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.5130 - mae: 2.2767

 297/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.7342 - mae: 2.2895

 315/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.8278 - mae: 2.2949

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.0294 - mae: 2.3078

 367/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.1487 - mae: 2.3172

 383/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.2348 - mae: 2.3250

 401/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.3666 - mae: 2.3349

 422/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.5343 - mae: 2.3463

 441/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.6736 - mae: 2.3571

 459/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.7952 - mae: 2.3665

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.8745 - mae: 2.3724

 484/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.9275 - mae: 2.3763

 494/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 10.9697 - mae: 2.3792

 503/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.0039 - mae: 2.3816

 512/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.0345 - mae: 2.3837

 525/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.0758 - mae: 2.3865

 534/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1061 - mae: 2.3886

 545/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1407 - mae: 2.3912

 561/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1845 - mae: 2.3942

 588/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.2677 - mae: 2.4008

 609/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3283 - mae: 2.4063

 628/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.3825 - mae: 2.4114

 636/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.4033 - mae: 2.4134

 644/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.4248 - mae: 2.4155

 653/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.4486 - mae: 2.4179

 666/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.4788 - mae: 2.4207

 680/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.5069 - mae: 2.4234

 698/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.5417 - mae: 2.4266

 722/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.5894 - mae: 2.4310

 742/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6261 - mae: 2.4344

 754/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6519 - mae: 2.4367

 763/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.6718 - mae: 2.4385

 776/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7002 - mae: 2.4412

 785/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7186 - mae: 2.4430

 795/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7371 - mae: 2.4449

 805/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7549 - mae: 2.4467

 816/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7728 - mae: 2.4486

 826/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.7873 - mae: 2.4502

 843/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.8108 - mae: 2.4530

 856/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8272 - mae: 2.4550

 866/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8382 - mae: 2.4564

 876/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8481 - mae: 2.4577

 897/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8668 - mae: 2.4602

 923/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8850 - mae: 2.4627

 943/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.8982 - mae: 2.4646

 971/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9155 - mae: 2.4671

 988/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9241 - mae: 2.4686

1014/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9330 - mae: 2.4703

1045/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9405 - mae: 2.4721

1069/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9431 - mae: 2.4731

1082/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 11.9465 - mae: 2.4737

1094/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9490 - mae: 2.4743

1112/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9527 - mae: 2.4752

1132/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9556 - mae: 2.4761

1158/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9572 - mae: 2.4771

1183/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9575 - mae: 2.4779

1206/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9559 - mae: 2.4785

1224/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9549 - mae: 2.4791

1242/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9537 - mae: 2.4797

1251/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9530 - mae: 2.4800

1260/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9522 - mae: 2.4803

1274/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9527 - mae: 2.4809

1283/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9529 - mae: 2.4812

1292/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9525 - mae: 2.4815

1298/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9524 - mae: 2.4817

1314/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9526 - mae: 2.4823

1335/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9512 - mae: 2.4828

1356/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9494 - mae: 2.4832

1371/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9476 - mae: 2.4835

1379/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9464 - mae: 2.4836

1392/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9445 - mae: 2.4838

1402/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9431 - mae: 2.4839

1411/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9416 - mae: 2.4840

1419/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9401 - mae: 2.4841

1426/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9390 - mae: 2.4841

1436/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 11.9379 - mae: 2.4843

1445/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9367 - mae: 2.4844

1453/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9355 - mae: 2.4845

1466/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9330 - mae: 2.4846

1475/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9311 - mae: 2.4847

1485/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9288 - mae: 2.4847

1498/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9255 - mae: 2.4848

1511/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9221 - mae: 2.4848

1527/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9172 - mae: 2.4847

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.9071 - mae: 2.4846

1596/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8952 - mae: 2.4844

1617/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8891 - mae: 2.4844

1635/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8850 - mae: 2.4845

1655/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8806 - mae: 2.4846

1676/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8750 - mae: 2.4845

1700/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8683 - mae: 2.4844

1718/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 11.8640 - mae: 2.4844

1737/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8607 - mae: 2.4846

1757/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8569 - mae: 2.4847

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8489 - mae: 2.4846

1829/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8369 - mae: 2.4842

1863/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8257 - mae: 2.4838

1900/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8121 - mae: 2.4832

1921/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8045 - mae: 2.4828

1929/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.8017 - mae: 2.4827

1938/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.7985 - mae: 2.4826

1969/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.7873 - mae: 2.4821

2000/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 11.7749 - mae: 2.4814

2024/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7651 - mae: 2.4808

2045/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7580 - mae: 2.4804

2055/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7543 - mae: 2.4801

2067/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7498 - mae: 2.4798

2078/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7456 - mae: 2.4795

2090/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7408 - mae: 2.4792

2100/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7367 - mae: 2.4789

2112/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7322 - mae: 2.4785

2125/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7274 - mae: 2.4781

2148/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7193 - mae: 2.4775

2172/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7107 - mae: 2.4768

2182/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7070 - mae: 2.4765

2191/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.7038 - mae: 2.4763

2206/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6986 - mae: 2.4759

2226/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6916 - mae: 2.4754

2245/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6846 - mae: 2.4749

2256/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6805 - mae: 2.4746

2273/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6739 - mae: 2.4740

2290/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6673 - mae: 2.4735

2304/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6619 - mae: 2.4731

2319/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6560 - mae: 2.4727

2344/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6459 - mae: 2.4719

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.6807 - mae: 2.3970

Epoch 19/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:35 41ms/step - loss: 1.2411 - mae: 1.1140

  22/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3.4873 - mae: 1.5135

  40/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 5.1285 - mae: 1.7385

  52/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 5.7019 - mae: 1.8183

  64/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 5.9993 - mae: 1.8609

  94/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.3356 - mae: 1.9042

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 6.6341 - mae: 1.9462

 165/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.8170 - mae: 1.9748

 195/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.9883 - mae: 2.0014

 221/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0843 - mae: 2.0173

 240/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1517 - mae: 2.0269

 261/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1937 - mae: 2.0340

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.2612 - mae: 2.0433

 310/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.2982 - mae: 2.0480

 329/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3591 - mae: 2.0556

 351/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.4326 - mae: 2.0649

 375/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5118 - mae: 2.0753

 394/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5645 - mae: 2.0820

 410/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6051 - mae: 2.0871

 425/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6619 - mae: 2.0934

 444/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.7621 - mae: 2.1036

 458/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.8502 - mae: 2.1121

 471/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.9233 - mae: 2.1190

 482/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.9834 - mae: 2.1247

 499/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.0765 - mae: 2.1339

 512/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.1421 - mae: 2.1405

 528/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.2186 - mae: 2.1481

 555/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.3514 - mae: 2.1614

 584/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.5121 - mae: 2.1772

 604/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.6100 - mae: 2.1868

 623/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.6949 - mae: 2.1948

 644/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.7911 - mae: 2.2041

 660/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.8678 - mae: 2.2114

 682/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.9657 - mae: 2.2207

 700/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.0395 - mae: 2.2278

 716/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1011 - mae: 2.2338

 731/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1549 - mae: 2.2389

 746/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2044 - mae: 2.2437

 765/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2609 - mae: 2.2492

 787/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.3189 - mae: 2.2547

 804/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.3630 - mae: 2.2589

 819/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.4000 - mae: 2.2624

 846/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.4616 - mae: 2.2685

 879/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.5236 - mae: 2.2744

 905/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.5662 - mae: 2.2785

 926/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.5988 - mae: 2.2817

 947/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6281 - mae: 2.2847

 971/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6592 - mae: 2.2880

 992/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6872 - mae: 2.2911

1006/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7071 - mae: 2.2932

1015/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7191 - mae: 2.2945

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7303 - mae: 2.2957

1033/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7409 - mae: 2.2968

1041/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7499 - mae: 2.2978

1050/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7600 - mae: 2.2989

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.7878 - mae: 2.3019

1105/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8201 - mae: 2.3054

1130/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8477 - mae: 2.3085

1143/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8622 - mae: 2.3100

1154/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8750 - mae: 2.3114

1170/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8938 - mae: 2.3135

1188/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9132 - mae: 2.3156

1206/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9307 - mae: 2.3175

1227/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.9508 - mae: 2.3197

1249/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.9739 - mae: 2.3223

1268/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.9990 - mae: 2.3245

1288/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0289 - mae: 2.3270

1305/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0532 - mae: 2.3290

1313/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0641 - mae: 2.3299

1330/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0857 - mae: 2.3316

1339/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.0965 - mae: 2.3324

1353/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.1128 - mae: 2.3337

1367/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.1290 - mae: 2.3350

1382/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.1462 - mae: 2.3363

1417/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.1835 - mae: 2.3391

1450/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.2151 - mae: 2.3413

1479/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.2400 - mae: 2.3430

1515/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.2663 - mae: 2.3446

1545/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.2844 - mae: 2.3456

1571/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 10.2981 - mae: 2.3462

1602/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3138 - mae: 2.3472

1621/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3227 - mae: 2.3477

1632/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3277 - mae: 2.3479

1644/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3332 - mae: 2.3483

1664/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3420 - mae: 2.3488

1685/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3506 - mae: 2.3494

1713/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3617 - mae: 2.3502

1730/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3690 - mae: 2.3506

1749/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3809 - mae: 2.3514

1762/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3892 - mae: 2.3519

1777/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.3984 - mae: 2.3526

1794/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4085 - mae: 2.3533

1801/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4127 - mae: 2.3536

1809/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4175 - mae: 2.3539

1816/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4218 - mae: 2.3542

1826/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4277 - mae: 2.3546

1846/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4391 - mae: 2.3555

1875/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4537 - mae: 2.3565

1896/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4634 - mae: 2.3572

1914/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4710 - mae: 2.3577

1926/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4759 - mae: 2.3580

1938/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4806 - mae: 2.3584

1944/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4829 - mae: 2.3585

1950/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4851 - mae: 2.3587

1959/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4884 - mae: 2.3589

1971/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4929 - mae: 2.3592

1983/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 10.4972 - mae: 2.3594

2003/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5042 - mae: 2.3599

2023/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5108 - mae: 2.3603

2040/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5160 - mae: 2.3606

2056/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5208 - mae: 2.3609

2067/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5242 - mae: 2.3611

2083/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5292 - mae: 2.3614

2108/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5362 - mae: 2.3618

2125/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5404 - mae: 2.3620

2155/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5465 - mae: 2.3623

2180/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5504 - mae: 2.3623

2204/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5536 - mae: 2.3624

2225/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5558 - mae: 2.3623

2241/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5573 - mae: 2.3623

2252/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5583 - mae: 2.3623

2261/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5590 - mae: 2.3622

2275/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5599 - mae: 2.3622

2291/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5611 - mae: 2.3621

2309/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5622 - mae: 2.3620

2324/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5633 - mae: 2.3620

2342/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.5645 - mae: 2.3620

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.7074 - mae: 2.3531

Epoch 20/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 2:03 52ms/step - loss: 0.0505 - mae: 0.2248

  16/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 5.6737 - mae: 1.8298

  29/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 7.1572 - mae: 2.0118

  38/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 7.4533 - mae: 2.0400

  47/2350 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 7.7429 - mae: 2.0791

  56/2350 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 7.8887 - mae: 2.1006

  61/2350 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 7.9581 - mae: 2.1144

  71/2350 ━━━━━━━━━━━━━━━━━━━━ 12s 5ms/step - loss: 8.0930 - mae: 2.1418

  84/2350 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 8.2336 - mae: 2.1648

  98/2350 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 8.4199 - mae: 2.1823

 123/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 8.5205 - mae: 2.1932

 140/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 8.6160 - mae: 2.1943

 151/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 8.7124 - mae: 2.1987

 161/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 8.7829 - mae: 2.2036

 174/2350 ━━━━━━━━━━━━━━━━━━━━ 9s 4ms/step - loss: 8.8658 - mae: 2.2108

 193/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 8.9793 - mae: 2.2227

 217/2350 ━━━━━━━━━━━━━━━━━━━━ 8s 4ms/step - loss: 9.1236 - mae: 2.2394

 239/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.2197 - mae: 2.2534

 262/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.2910 - mae: 2.2638

 280/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.3375 - mae: 2.2709

 291/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.3550 - mae: 2.2737

 304/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.3727 - mae: 2.2768

 315/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.3858 - mae: 2.2793

 332/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.4034 - mae: 2.2830

 353/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 4ms/step - loss: 9.4243 - mae: 2.2877

 376/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4388 - mae: 2.2914

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4450 - mae: 2.2940

 416/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4466 - mae: 2.2959

 433/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4478 - mae: 2.2972

 452/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4408 - mae: 2.2973

 471/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4275 - mae: 2.2962

 494/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.4177 - mae: 2.2958

 518/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.4077 - mae: 2.2956

 534/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.4038 - mae: 2.2959

 552/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3970 - mae: 2.2959

 569/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3894 - mae: 2.2957

 587/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3828 - mae: 2.2955

 610/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3723 - mae: 2.2949

 635/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3557 - mae: 2.2936

 661/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3446 - mae: 2.2923

 686/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.3364 - mae: 2.2915

 709/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3279 - mae: 2.2906

 730/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3203 - mae: 2.2900

 737/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3183 - mae: 2.2899

 745/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3160 - mae: 2.2898

 761/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3112 - mae: 2.2895

 779/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.3038 - mae: 2.2889

 794/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2957 - mae: 2.2880

 813/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2834 - mae: 2.2866

 839/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2646 - mae: 2.2844

 852/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2551 - mae: 2.2833

 861/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2488 - mae: 2.2826

 869/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2431 - mae: 2.2819

 878/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2369 - mae: 2.2811

 888/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2293 - mae: 2.2802

 900/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2197 - mae: 2.2789

 910/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2114 - mae: 2.2778

 922/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.2012 - mae: 2.2765

 940/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1863 - mae: 2.2747

 973/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1601 - mae: 2.2713

1006/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1353 - mae: 2.2682

1034/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 9.1251 - mae: 2.2664

1059/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1218 - mae: 2.2655

1085/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1187 - mae: 2.2647

1112/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1167 - mae: 2.2637

1128/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1181 - mae: 2.2634

1145/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1187 - mae: 2.2629

1156/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1187 - mae: 2.2626

1164/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1186 - mae: 2.2624

1173/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1197 - mae: 2.2622

1184/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1218 - mae: 2.2621

1197/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1245 - mae: 2.2621

1205/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1261 - mae: 2.2620

1213/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1277 - mae: 2.2620

1223/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1297 - mae: 2.2620

1243/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1334 - mae: 2.2619

1277/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1427 - mae: 2.2620

1298/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1504 - mae: 2.2621

1318/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1572 - mae: 2.2623

1338/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1643 - mae: 2.2625

1358/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.1714 - mae: 2.2628

1378/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.1785 - mae: 2.2631

1397/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.1851 - mae: 2.2633

1416/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.1912 - mae: 2.2634

1437/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.1976 - mae: 2.2636

1469/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2061 - mae: 2.2638

1507/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2164 - mae: 2.2641

1544/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2243 - mae: 2.2641

1562/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2274 - mae: 2.2640

1571/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2288 - mae: 2.2639

1577/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2298 - mae: 2.2639

1594/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2331 - mae: 2.2639

1608/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2357 - mae: 2.2639

1626/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2400 - mae: 2.2640

1640/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2437 - mae: 2.2642

1650/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 9.2465 - mae: 2.2644

1677/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2547 - mae: 2.2649

1698/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2611 - mae: 2.2654

1718/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2674 - mae: 2.2658

1735/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2727 - mae: 2.2662

1751/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2773 - mae: 2.2665

1775/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2838 - mae: 2.2670

1803/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2899 - mae: 2.2673

1826/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2945 - mae: 2.2675

1848/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.2988 - mae: 2.2677

1882/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3041 - mae: 2.2680

1902/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3064 - mae: 2.2680

1923/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3086 - mae: 2.2680

1945/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3105 - mae: 2.2680

1964/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3121 - mae: 2.2680

1982/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3134 - mae: 2.2680

1999/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.3146 - mae: 2.2680

2011/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3154 - mae: 2.2680

2024/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3161 - mae: 2.2679

2040/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3172 - mae: 2.2679

2060/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3185 - mae: 2.2678

2078/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3200 - mae: 2.2678

2097/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3216 - mae: 2.2679

2112/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3230 - mae: 2.2679

2130/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3245 - mae: 2.2680

2148/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3255 - mae: 2.2679

2160/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3262 - mae: 2.2679

2169/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3268 - mae: 2.2679

2179/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3273 - mae: 2.2679

2192/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3280 - mae: 2.2679

2199/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3285 - mae: 2.2679

2207/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3290 - mae: 2.2678

2217/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3294 - mae: 2.2678

2227/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3298 - mae: 2.2678

2251/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3304 - mae: 2.2677

2270/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3309 - mae: 2.2676

2288/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3318 - mae: 2.2676

2304/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3327 - mae: 2.2676

2313/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3335 - mae: 2.2676

2325/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3346 - mae: 2.2677

2341/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.3362 - mae: 2.2678

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 9.6338 - mae: 2.2868

Epoch 21/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 3:01 77ms/step - loss: 0.9701 - mae: 0.9849

   8/2350 ━━━━━━━━━━━━━━━━━━━━ 17s 7ms/step - loss: 9.4657 - mae: 2.3668

  18/2350 ━━━━━━━━━━━━━━━━━━━━ 13s 6ms/step - loss: 11.1053 - mae: 2.5598

  31/2350 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 10.6298 - mae: 2.5085

  41/2350 ━━━━━━━━━━━━━━━━━━━━ 11s 5ms/step - loss: 10.7965 - mae: 2.5487

  56/2350 ━━━━━━━━━━━━━━━━━━━━ 10s 5ms/step - loss: 10.7850 - mae: 2.5673

  92/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 10.3365 - mae: 2.5426

 136/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.7359 - mae: 2.4773

 168/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 11.3603 - mae: 2.5099

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 12.3659 - mae: 2.5413

 236/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.4100 - mae: 2.5768

 264/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 13.9526 - mae: 2.6047

 283/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.2353 - mae: 2.6214

 304/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.4726 - mae: 2.6367

 333/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.7146 - mae: 2.6544

 350/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.8183 - mae: 2.6625

 364/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.8915 - mae: 2.6687

 379/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 14.9578 - mae: 2.6749

 394/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0182 - mae: 2.6813

 406/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.0563 - mae: 2.6858

 420/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 15.1070 - mae: 2.6914

 431/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.1383 - mae: 2.6953

 444/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.1674 - mae: 2.6992

 457/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.1907 - mae: 2.7027

 469/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.2051 - mae: 2.7050

 482/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2230 - mae: 2.7075

 495/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2417 - mae: 2.7103

 508/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2547 - mae: 2.7126

 521/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2613 - mae: 2.7144

 534/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2643 - mae: 2.7159

 555/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2572 - mae: 2.7171

 570/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2442 - mae: 2.7172

 584/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2273 - mae: 2.7167

 597/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.2092 - mae: 2.7160

 610/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.1867 - mae: 2.7149

 626/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.1540 - mae: 2.7128

 638/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.1283 - mae: 2.7112

 650/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 15.1013 - mae: 2.7094

 669/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.0593 - mae: 2.7065

 683/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.0285 - mae: 2.7043

 697/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 15.0052 - mae: 2.7024

 710/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.9832 - mae: 2.7008

 721/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.9638 - mae: 2.6993

 739/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.9374 - mae: 2.6975

 759/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.9115 - mae: 2.6959

 775/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.8868 - mae: 2.6942

 797/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.8494 - mae: 2.6914

 826/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.7949 - mae: 2.6874

 846/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.7534 - mae: 2.6842

 870/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.6998 - mae: 2.6800

 902/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.6260 - mae: 2.6741

 930/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 14.5624 - mae: 2.6691

 964/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.4860 - mae: 2.6634

 985/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.4379 - mae: 2.6597

1001/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.3998 - mae: 2.6567

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.3445 - mae: 2.6523

1050/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.2822 - mae: 2.6472

1077/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.2188 - mae: 2.6419

1101/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.1664 - mae: 2.6377

1121/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.1244 - mae: 2.6344

1141/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.0854 - mae: 2.6314

1160/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.0495 - mae: 2.6288

1181/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 14.0092 - mae: 2.6257

1203/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.9673 - mae: 2.6224

1224/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 13.9334 - mae: 2.6197

1246/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8979 - mae: 2.6168

1272/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8561 - mae: 2.6133

1293/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.8240 - mae: 2.6107

1312/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7959 - mae: 2.6084

1337/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7587 - mae: 2.6054

1360/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.7280 - mae: 2.6029

1381/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6999 - mae: 2.6007

1402/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6720 - mae: 2.5985

1428/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6372 - mae: 2.5958

1454/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.6019 - mae: 2.5929

1472/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.5782 - mae: 2.5910

1487/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.5586 - mae: 2.5894

1499/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.5429 - mae: 2.5881

1518/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.5180 - mae: 2.5861

1540/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4912 - mae: 2.5840

1549/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4803 - mae: 2.5832

1554/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4743 - mae: 2.5827

1565/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4611 - mae: 2.5817

1579/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4443 - mae: 2.5805

1596/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 13.4237 - mae: 2.5790

1621/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3945 - mae: 2.5767

1652/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3601 - mae: 2.5741

1685/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.3231 - mae: 2.5711

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.2891 - mae: 2.5684

1750/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.2514 - mae: 2.5654

1777/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.2234 - mae: 2.5632

1810/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.1894 - mae: 2.5606

1842/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.1566 - mae: 2.5582

1869/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.1281 - mae: 2.5559

1899/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.0967 - mae: 2.5534

1930/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.0650 - mae: 2.5509

1942/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 13.0535 - mae: 2.5499

1964/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0327 - mae: 2.5482

1989/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 13.0091 - mae: 2.5463

2021/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9792 - mae: 2.5437

2060/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.9435 - mae: 2.5407

2093/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9128 - mae: 2.5381

2132/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8781 - mae: 2.5351

2166/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8481 - mae: 2.5325

2199/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8188 - mae: 2.5300

2225/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7956 - mae: 2.5280

2237/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7850 - mae: 2.5270

2259/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7665 - mae: 2.5255

2278/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7508 - mae: 2.5242

2298/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7345 - mae: 2.5228

2315/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7212 - mae: 2.5217

2332/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7087 - mae: 2.5207

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 10.9892 - mae: 2.3827

Epoch 22/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:02 27ms/step - loss: 64.1014 - mae: 8.0063

  33/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.9453 - mae: 2.8546

  61/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.1827 - mae: 2.5352

  83/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.1018 - mae: 2.4045

 101/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.5468 - mae: 2.3423

 111/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.3280 - mae: 2.3180

 127/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.0850 - mae: 2.2884

 145/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.8176 - mae: 2.2528

 166/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.5732 - mae: 2.2200

 203/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.3115 - mae: 2.1838

 231/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.2012 - mae: 2.1710

 248/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1862 - mae: 2.1679

 269/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1719 - mae: 2.1632

 290/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1655 - mae: 2.1599

 312/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1659 - mae: 2.1586

 334/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1629 - mae: 2.1570

 354/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1665 - mae: 2.1569

 365/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1691 - mae: 2.1571

 374/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.1695 - mae: 2.1571

 383/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1716 - mae: 2.1573

 390/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1726 - mae: 2.1576

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1731 - mae: 2.1579

 405/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1725 - mae: 2.1581

 414/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1729 - mae: 2.1586

 442/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1741 - mae: 2.1603

 466/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1751 - mae: 2.1616

 491/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 8.1709 - mae: 2.1623

 520/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.1602 - mae: 2.1623

 559/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.1607 - mae: 2.1633

 599/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 8.2050 - mae: 2.1674

 637/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.2480 - mae: 2.1723

 674/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2860 - mae: 2.1769

 703/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3252 - mae: 2.1810

 717/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3440 - mae: 2.1829

 728/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3589 - mae: 2.1845

 759/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3952 - mae: 2.1887

 784/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4190 - mae: 2.1915

 806/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4405 - mae: 2.1939

 827/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4599 - mae: 2.1961

 847/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4775 - mae: 2.1979

 864/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4905 - mae: 2.1992

 879/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5022 - mae: 2.2004

 899/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5155 - mae: 2.2017

 918/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5264 - mae: 2.2027

 939/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5369 - mae: 2.2037

 960/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5468 - mae: 2.2047

 976/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5544 - mae: 2.2054

 994/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5618 - mae: 2.2061

1012/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5685 - mae: 2.2068

1022/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5724 - mae: 2.2073

1031/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.5760 - mae: 2.2077

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.5811 - mae: 2.2083

1065/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.5928 - mae: 2.2097

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.6053 - mae: 2.2111

1103/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.6196 - mae: 2.2126

1121/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.6332 - mae: 2.2141

1137/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.6455 - mae: 2.2154

1155/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 8.6597 - mae: 2.2171

1195/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 3ms/step - loss: 8.6893 - mae: 2.2204

1232/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7128 - mae: 2.2229

1262/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7280 - mae: 2.2244

1277/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7349 - mae: 2.2251

1303/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7467 - mae: 2.2261

1315/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7521 - mae: 2.2265

1330/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7587 - mae: 2.2270

1347/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7661 - mae: 2.2276

1382/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7815 - mae: 2.2291

1421/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7967 - mae: 2.2304

1456/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8077 - mae: 2.2314

1485/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8157 - mae: 2.2321

1514/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8223 - mae: 2.2326

1544/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8320 - mae: 2.2335

1567/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8417 - mae: 2.2344

1586/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8495 - mae: 2.2352

1616/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8620 - mae: 2.2365

1635/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8701 - mae: 2.2374

1654/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8773 - mae: 2.2382

1670/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8827 - mae: 2.2387

1681/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8861 - mae: 2.2391

1689/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8884 - mae: 2.2394

1697/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8907 - mae: 2.2396

1704/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8926 - mae: 2.2398

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8955 - mae: 2.2401

1736/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9007 - mae: 2.2407

1757/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9064 - mae: 2.2414

1780/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9125 - mae: 2.2420

1799/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9169 - mae: 2.2425

1817/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9214 - mae: 2.2430

1839/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9270 - mae: 2.2437

1857/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9310 - mae: 2.2441

1874/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9345 - mae: 2.2445

1894/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9391 - mae: 2.2450

1912/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9432 - mae: 2.2454

1935/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9487 - mae: 2.2460

1959/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9546 - mae: 2.2467

1980/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9598 - mae: 2.2472

2004/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9654 - mae: 2.2478

2027/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9699 - mae: 2.2482

2049/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9738 - mae: 2.2486

2072/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9783 - mae: 2.2490

2096/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9823 - mae: 2.2493

2117/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9856 - mae: 2.2496

2134/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9886 - mae: 2.2499

2145/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9907 - mae: 2.2501

2153/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9921 - mae: 2.2503

2162/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9937 - mae: 2.2504

2188/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.9984 - mae: 2.2509

2222/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0040 - mae: 2.2515

2254/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0093 - mae: 2.2521

2282/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0136 - mae: 2.2526

2316/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0184 - mae: 2.2532

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.0227 - mae: 2.2537

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 9.4097 - mae: 2.2923

Epoch 23/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 59s 26ms/step - loss: 8.9659 - mae: 2.9943

  44/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 1ms/step - loss: 10.6636 - mae: 2.7770

  77/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 11.3713 - mae: 2.7570

 107/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 11.6407 - mae: 2.7608

 127/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.8352 - mae: 2.7755

 162/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.0667 - mae: 2.7818

 195/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.0095 - mae: 2.7640

 225/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.8742 - mae: 2.7397

 243/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.7745 - mae: 2.7238

 262/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.6514 - mae: 2.7041

 282/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.5132 - mae: 2.6811

 304/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.3678 - mae: 2.6572

 327/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.2418 - mae: 2.6356

 350/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.1217 - mae: 2.6150

 370/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.0214 - mae: 2.5984

 390/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.9291 - mae: 2.5827

 409/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.8481 - mae: 2.5685

 433/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.7412 - mae: 2.5502

 452/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.6559 - mae: 2.5361

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.5670 - mae: 2.5211

 492/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.4946 - mae: 2.5089

 515/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.4056 - mae: 2.4944

 533/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.3470 - mae: 2.4842

 545/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.3167 - mae: 2.4784

 555/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.2925 - mae: 2.4739

 568/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.2660 - mae: 2.4686

 586/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.2379 - mae: 2.4622

 601/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.2139 - mae: 2.4567

 617/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.1869 - mae: 2.4510

 629/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.1663 - mae: 2.4468

 649/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 10.1324 - mae: 2.4402

 674/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0973 - mae: 2.4327

 692/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0800 - mae: 2.4282

 710/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0691 - mae: 2.4245

 732/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0579 - mae: 2.4204

 745/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0529 - mae: 2.4182

 756/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0516 - mae: 2.4165

 773/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0479 - mae: 2.4138

 789/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0452 - mae: 2.4113

 800/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0421 - mae: 2.4096

 816/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0362 - mae: 2.4070

 832/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0283 - mae: 2.4042

 847/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0193 - mae: 2.4014

 868/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0099 - mae: 2.3981

 888/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 10.0023 - mae: 2.3952

 907/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9928 - mae: 2.3922

 925/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9836 - mae: 2.3894

 944/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9752 - mae: 2.3865

 960/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9698 - mae: 2.3843

 977/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9636 - mae: 2.3821

 997/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9559 - mae: 2.3796

1015/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9480 - mae: 2.3772

1029/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9410 - mae: 2.3754

1039/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9356 - mae: 2.3740

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.9128 - mae: 2.3688

1111/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8900 - mae: 2.3638

1143/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 9.8697 - mae: 2.3596

1177/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8493 - mae: 2.3555

1211/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8286 - mae: 2.3514

1243/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8102 - mae: 2.3479

1257/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8033 - mae: 2.3465

1283/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7910 - mae: 2.3440

1315/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7760 - mae: 2.3411

1346/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7601 - mae: 2.3381

1367/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7493 - mae: 2.3361

1387/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7395 - mae: 2.3343

1407/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7292 - mae: 2.3324

1425/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7223 - mae: 2.3309

1444/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7150 - mae: 2.3293

1464/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7070 - mae: 2.3276

1482/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7002 - mae: 2.3263

1500/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6930 - mae: 2.3248

1519/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6851 - mae: 2.3233

1538/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6769 - mae: 2.3217

1556/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6692 - mae: 2.3203

1573/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6618 - mae: 2.3189

1588/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6554 - mae: 2.3177

1605/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6479 - mae: 2.3164

1627/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6378 - mae: 2.3147

1648/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6284 - mae: 2.3131

1662/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6220 - mae: 2.3120

1673/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6167 - mae: 2.3111

1693/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.6069 - mae: 2.3096

1723/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5930 - mae: 2.3073

1734/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5887 - mae: 2.3066

1747/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.5839 - mae: 2.3057

1763/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.5783 - mae: 2.3048

1777/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.5738 - mae: 2.3040

1810/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 3ms/step - loss: 9.5636 - mae: 2.3023

1853/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5499 - mae: 2.3001

1899/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5370 - mae: 2.2981

1932/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5290 - mae: 2.2967

1951/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.5240 - mae: 2.2959

1970/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.5194 - mae: 2.2951

1990/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.5146 - mae: 2.2943

2013/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.5090 - mae: 2.2933

2055/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4996 - mae: 2.2916

2095/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4904 - mae: 2.2900

2129/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4816 - mae: 2.2885

2162/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4737 - mae: 2.2872

2197/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4658 - mae: 2.2859

2230/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4589 - mae: 2.2847

2256/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4531 - mae: 2.2837

2290/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4459 - mae: 2.2824

2322/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4398 - mae: 2.2814

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.2235 - mae: 2.2210

Epoch 24/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:55 49ms/step - loss: 0.5711 - mae: 0.7557

  26/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.7454 - mae: 2.0389

  50/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.5116 - mae: 2.2706

  72/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.9830 - mae: 2.3398

  92/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.3971 - mae: 2.3840

 102/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 9.6361 - mae: 2.4039

 116/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.7954 - mae: 2.4130

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.8555 - mae: 2.4112

 145/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 9.8936 - mae: 2.4098

 154/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.0245 - mae: 2.4132

 168/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.3589 - mae: 2.4281

 204/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.1623 - mae: 2.4806

 238/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 11.9460 - mae: 2.5366

 268/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 12.4295 - mae: 2.5716

 288/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.6914 - mae: 2.5923

 306/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.8589 - mae: 2.6044

 323/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 12.9763 - mae: 2.6127

 339/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.0548 - mae: 2.6178

 354/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1021 - mae: 2.6202

 371/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1351 - mae: 2.6209

 385/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1530 - mae: 2.6211

 398/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1608 - mae: 2.6209

 411/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1604 - mae: 2.6199

 428/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1655 - mae: 2.6190

 448/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1661 - mae: 2.6182

 468/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1568 - mae: 2.6168

 488/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1392 - mae: 2.6147

 504/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.1168 - mae: 2.6120

 521/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.0876 - mae: 2.6084

 539/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 13.0569 - mae: 2.6045

 557/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 13.0343 - mae: 2.6017

 578/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 13.0080 - mae: 2.5986

 597/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9838 - mae: 2.5961

 611/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9637 - mae: 2.5941

 644/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.9133 - mae: 2.5893

 687/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.8325 - mae: 2.5812

 728/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.7508 - mae: 2.5726

 750/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 3ms/step - loss: 12.7155 - mae: 2.5686

 774/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.6879 - mae: 2.5654

 802/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 3ms/step - loss: 12.6519 - mae: 2.5613

 842/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5947 - mae: 2.5549

 863/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5636 - mae: 2.5516

 888/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5276 - mae: 2.5478

 927/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.4744 - mae: 2.5423

 954/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.4395 - mae: 2.5385

 970/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.4184 - mae: 2.5362

 990/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3952 - mae: 2.5337

1007/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3750 - mae: 2.5315

1025/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3530 - mae: 2.5290

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3311 - mae: 2.5266

1059/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.3115 - mae: 2.5244

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2913 - mae: 2.5222

1094/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2665 - mae: 2.5196

1128/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.2249 - mae: 2.5152

1161/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.1827 - mae: 2.5108

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.1385 - mae: 2.5064

1223/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.1059 - mae: 2.5032

1239/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.0863 - mae: 2.5013

1256/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.0649 - mae: 2.4991

1273/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.0431 - mae: 2.4968

1294/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 12.0163 - mae: 2.4941

1317/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.9871 - mae: 2.4911

1341/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.9565 - mae: 2.4879

1363/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.9302 - mae: 2.4851

1384/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.9072 - mae: 2.4826

1404/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.8857 - mae: 2.4804

1423/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.8652 - mae: 2.4782

1445/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.8415 - mae: 2.4758

1464/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.8218 - mae: 2.4739

1481/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.8041 - mae: 2.4722

1497/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.7872 - mae: 2.4705

1510/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 11.7732 - mae: 2.4691

1527/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.7569 - mae: 2.4674

1543/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.7437 - mae: 2.4659

1559/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.7311 - mae: 2.4645

1577/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.7172 - mae: 2.4631

1594/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.7043 - mae: 2.4618

1612/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6906 - mae: 2.4604

1631/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6760 - mae: 2.4589

1650/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6614 - mae: 2.4575

1669/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6472 - mae: 2.4561

1687/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6335 - mae: 2.4547

1706/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.6194 - mae: 2.4533

1739/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5999 - mae: 2.4514

1779/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5787 - mae: 2.4494

1814/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5611 - mae: 2.4477

1852/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5426 - mae: 2.4458

1883/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5277 - mae: 2.4443

1916/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 11.5151 - mae: 2.4431

1945/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.5038 - mae: 2.4420

1964/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4969 - mae: 2.4413

1993/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4865 - mae: 2.4403

2020/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4772 - mae: 2.4394

2039/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4711 - mae: 2.4388

2060/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4643 - mae: 2.4382

2083/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4566 - mae: 2.4375

2107/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4484 - mae: 2.4368

2130/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4403 - mae: 2.4361

2152/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4325 - mae: 2.4354

2179/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4225 - mae: 2.4345

2209/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4108 - mae: 2.4334

2227/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.4038 - mae: 2.4327

2249/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3956 - mae: 2.4320

2270/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3885 - mae: 2.4314

2290/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3813 - mae: 2.4307

2311/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3740 - mae: 2.4301

2334/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 11.3659 - mae: 2.4294

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 2ms/step - loss: 10.4797 - mae: 2.3538

Epoch 25/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:03 27ms/step - loss: 2.2265 - mae: 1.4922

  25/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.2045 - mae: 1.4766

  67/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3.4765 - mae: 1.4659

  85/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.5625 - mae: 1.4666

 105/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.7304 - mae: 1.4738

 123/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.8915 - mae: 1.4874

 134/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 4.0025 - mae: 1.5020

 163/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.5524 - mae: 1.5608

 190/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.0426 - mae: 1.6152

 211/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.3288 - mae: 1.6496

 230/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.5736 - mae: 1.6813

 252/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.8172 - mae: 1.7146

 274/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.0212 - mae: 1.7453

 296/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.2053 - mae: 1.7736

 317/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.3406 - mae: 1.7954

 337/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.4464 - mae: 1.8130

 355/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.5318 - mae: 1.8273

 373/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.6191 - mae: 1.8412

 416/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.8876 - mae: 1.8767

 457/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0940 - mae: 1.9049

 489/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2150 - mae: 1.9226

 524/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3343 - mae: 1.9408

 553/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4281 - mae: 1.9553

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4955 - mae: 1.9658

 610/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5873 - mae: 1.9805

 644/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.6628 - mae: 1.9932

 677/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7291 - mae: 2.0049

 712/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7865 - mae: 2.0153

 730/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8113 - mae: 2.0198

 751/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8337 - mae: 2.0239

 784/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8631 - mae: 2.0295

 812/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8887 - mae: 2.0344

 832/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9057 - mae: 2.0377

 853/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9223 - mae: 2.0410

 872/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9375 - mae: 2.0440

 888/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9513 - mae: 2.0466

 902/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9618 - mae: 2.0487

 919/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9748 - mae: 2.0513

 931/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9832 - mae: 2.0529

 952/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9982 - mae: 2.0557

 983/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.0249 - mae: 2.0601

1015/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.0512 - mae: 2.0647

1040/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.0748 - mae: 2.0685

1062/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.0956 - mae: 2.0721

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1148 - mae: 2.0755

1108/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1345 - mae: 2.0790

1122/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1445 - mae: 2.0809

1153/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1632 - mae: 2.0845

1168/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1713 - mae: 2.0862

1189/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1826 - mae: 2.0884

1207/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1908 - mae: 2.0901

1229/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1994 - mae: 2.0920

1263/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2133 - mae: 2.0948

1291/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2243 - mae: 2.0969

1316/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2327 - mae: 2.0986

1337/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2385 - mae: 2.0998

1361/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2439 - mae: 2.1010

1384/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2479 - mae: 2.1021

1397/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2499 - mae: 2.1026

1409/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2523 - mae: 2.1032

1421/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2555 - mae: 2.1038

1448/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2623 - mae: 2.1054

1485/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2753 - mae: 2.1077

1507/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2850 - mae: 2.1092

1529/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2943 - mae: 2.1107

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3068 - mae: 2.1128

1594/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3193 - mae: 2.1148

1624/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3295 - mae: 2.1166

1650/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3376 - mae: 2.1180

1670/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3434 - mae: 2.1191

1693/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3502 - mae: 2.1202

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3563 - mae: 2.1213

1740/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3632 - mae: 2.1225

1764/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3725 - mae: 2.1237

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3857 - mae: 2.1253

1812/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3973 - mae: 2.1266

1835/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4086 - mae: 2.1279

1855/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4181 - mae: 2.1291

1879/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4282 - mae: 2.1302

1903/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4378 - mae: 2.1313

1925/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4466 - mae: 2.1323

1950/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4559 - mae: 2.1334

1978/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4661 - mae: 2.1346

2012/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4774 - mae: 2.1360

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4894 - mae: 2.1373

2077/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4986 - mae: 2.1384

2110/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5086 - mae: 2.1395

2145/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5190 - mae: 2.1407

2175/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5279 - mae: 2.1417

2199/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5348 - mae: 2.1425

2233/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5444 - mae: 2.1436

2277/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5579 - mae: 2.1452

2301/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5645 - mae: 2.1459

2325/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5704 - mae: 2.1466

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5760 - mae: 2.1472

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.0989 - mae: 2.2073

Epoch 26/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:03 27ms/step - loss: 3.1112 - mae: 1.7638

  27/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.1476 - mae: 1.4865

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.1990 - mae: 1.5869

  77/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.4479 - mae: 1.5828

 103/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.4707 - mae: 1.5686

 126/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.5735 - mae: 1.5748

 150/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.7819 - mae: 1.5957

 177/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.0034 - mae: 1.6230

 202/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.2564 - mae: 1.6576

 226/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.4284 - mae: 1.6822

 249/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.5561 - mae: 1.6986

 271/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.6834 - mae: 1.7159

 299/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.8040 - mae: 1.7333

 321/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.9080 - mae: 1.7483

 342/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.9840 - mae: 1.7592

 367/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.0515 - mae: 1.7698

 391/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.0995 - mae: 1.7782

 415/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.1404 - mae: 1.7855

 438/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.1809 - mae: 1.7929

 462/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.2356 - mae: 1.8016

 487/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.3281 - mae: 1.8133

 509/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.3929 - mae: 1.8214

 534/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4589 - mae: 1.8296

 558/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5188 - mae: 1.8371

 582/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5711 - mae: 1.8437

 610/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6251 - mae: 1.8507

 635/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6657 - mae: 1.8563

 660/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7068 - mae: 1.8619

 689/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7570 - mae: 1.8682

 713/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7894 - mae: 1.8723

 736/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8189 - mae: 1.8762

 763/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8481 - mae: 1.8802

 795/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8760 - mae: 1.8841

 839/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9175 - mae: 1.8903

 877/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9461 - mae: 1.8945

 910/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9695 - mae: 1.8980

 944/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0088 - mae: 1.9027

 976/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0675 - mae: 1.9086

1011/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1433 - mae: 1.9163

1032/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1941 - mae: 1.9215

1063/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.2658 - mae: 1.9287

1090/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3305 - mae: 1.9354

1116/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3919 - mae: 1.9418

1137/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4393 - mae: 1.9468

1161/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4941 - mae: 1.9526

1185/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.5483 - mae: 1.9583

1208/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.5997 - mae: 1.9639

1232/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6504 - mae: 1.9694

1261/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7062 - mae: 1.9756

1288/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7536 - mae: 1.9807

1312/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7926 - mae: 1.9849

1334/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8260 - mae: 1.9885

1358/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8623 - mae: 1.9923

1381/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8963 - mae: 1.9959

1408/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9340 - mae: 2.0000

1434/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9676 - mae: 2.0037

1457/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9950 - mae: 2.0067

1479/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0201 - mae: 2.0096

1503/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0477 - mae: 2.0127

1527/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0753 - mae: 2.0158

1558/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1084 - mae: 2.0195

1581/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1314 - mae: 2.0221

1607/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1555 - mae: 2.0248

1632/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1768 - mae: 2.0273

1658/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1978 - mae: 2.0297

1685/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2185 - mae: 2.0321

1714/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2388 - mae: 2.0345

1737/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2554 - mae: 2.0364

1763/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2767 - mae: 2.0388

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.2981 - mae: 2.0411

1814/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3173 - mae: 2.0433

1838/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.3344 - mae: 2.0452

1863/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3510 - mae: 2.0471

1887/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3658 - mae: 2.0488

1916/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3829 - mae: 2.0508

1942/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3976 - mae: 2.0526

1969/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4132 - mae: 2.0544

2003/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4330 - mae: 2.0568

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4607 - mae: 2.0600

2080/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4789 - mae: 2.0621

2110/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4946 - mae: 2.0639

2143/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5106 - mae: 2.0658

2178/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5261 - mae: 2.0676

2213/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5405 - mae: 2.0693

2258/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5579 - mae: 2.0715

2298/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5735 - mae: 2.0734

2329/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5844 - mae: 2.0748

2348/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5906 - mae: 2.0756

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.3224 - mae: 2.1720

Epoch 27/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 51s 22ms/step - loss: 11.4442 - mae: 3.3829

  39/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 6.1578 - mae: 2.0024

  63/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6324 - mae: 2.0327

  87/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.9653 - mae: 2.0807

 108/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.9992 - mae: 2.0844

 131/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1113 - mae: 2.0933

 156/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1460 - mae: 2.0922

 178/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1130 - mae: 2.0836

 212/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0428 - mae: 2.0674

 245/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9536 - mae: 2.0493

 271/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9438 - mae: 2.0434

 294/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9497 - mae: 2.0409

 314/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9797 - mae: 2.0421

 339/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.0249 - mae: 2.0442

 364/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.0627 - mae: 2.0454

 391/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.0888 - mae: 2.0453

 417/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1039 - mae: 2.0446

 442/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1235 - mae: 2.0449

 465/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1389 - mae: 2.0451

 491/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1547 - mae: 2.0453

 515/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1669 - mae: 2.0454

 538/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1799 - mae: 2.0460

 559/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1937 - mae: 2.0471

 589/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2115 - mae: 2.0487

 622/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2278 - mae: 2.0496

 646/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2395 - mae: 2.0506

 669/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2526 - mae: 2.0519

 693/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2670 - mae: 2.0534

 715/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2790 - mae: 2.0547

 738/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2889 - mae: 2.0557

 759/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2974 - mae: 2.0566

 780/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3043 - mae: 2.0573

 804/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3100 - mae: 2.0577

 829/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3178 - mae: 2.0584

 854/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3266 - mae: 2.0592

 877/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3370 - mae: 2.0602

 901/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3506 - mae: 2.0615

 927/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3660 - mae: 2.0631

 954/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3790 - mae: 2.0645

 982/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.3922 - mae: 2.0659

1009/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4030 - mae: 2.0669

1035/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4123 - mae: 2.0676

1062/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4209 - mae: 2.0683

1085/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4266 - mae: 2.0687

1108/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4336 - mae: 2.0692

1136/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4433 - mae: 2.0700

1161/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4503 - mae: 2.0706

1188/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4567 - mae: 2.0710

1211/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4620 - mae: 2.0714

1238/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4705 - mae: 2.0721

1262/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4798 - mae: 2.0728

1288/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.4915 - mae: 2.0736

1313/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.5020 - mae: 2.0742

1336/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.5107 - mae: 2.0748

1362/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.5210 - mae: 2.0756

1394/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.5386 - mae: 2.0772

1424/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.5627 - mae: 2.0793

1459/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.5923 - mae: 2.0820

1493/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.6219 - mae: 2.0847

1526/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.6495 - mae: 2.0871

1564/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.6781 - mae: 2.0895

1586/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.6949 - mae: 2.0909

1618/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.7186 - mae: 2.0930

1655/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.7431 - mae: 2.0950

1678/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.7576 - mae: 2.0963

1699/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.7713 - mae: 2.0975

1722/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.7866 - mae: 2.0988

1745/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8008 - mae: 2.1001

1767/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8138 - mae: 2.1012

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8267 - mae: 2.1023

1811/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8415 - mae: 2.1036

1834/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8571 - mae: 2.1050

1864/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8794 - mae: 2.1069

1881/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.8919 - mae: 2.1080

1903/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9075 - mae: 2.1093

1929/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9248 - mae: 2.1108

1955/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9411 - mae: 2.1121

1980/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9557 - mae: 2.1133

2004/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9697 - mae: 2.1145

2024/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9806 - mae: 2.1154

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9932 - mae: 2.1164

2074/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0068 - mae: 2.1175

2099/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0197 - mae: 2.1186

2121/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0311 - mae: 2.1195

2147/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0441 - mae: 2.1206

2175/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0575 - mae: 2.1218

2198/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0677 - mae: 2.1227

2222/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0778 - mae: 2.1235

2246/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0878 - mae: 2.1244

2266/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0958 - mae: 2.1251

2284/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1027 - mae: 2.1257

2317/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1142 - mae: 2.1267

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1243 - mae: 2.1275

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.8096 - mae: 2.1832

Epoch 28/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:16 33ms/step - loss: 5.9285 - mae: 2.4349

  29/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.5527 - mae: 1.5388

  44/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3.5501 - mae: 1.5474

  59/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 3.5948 - mae: 1.5573

  73/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 3.6555 - mae: 1.5602

  85/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 3.7794 - mae: 1.5748

 100/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 3.9701 - mae: 1.6008

 120/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 4.2898 - mae: 1.6359

 147/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 5.0558 - mae: 1.7100

 187/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 5.8233 - mae: 1.7926

 223/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.2100 - mae: 1.8405

 252/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.3872 - mae: 1.8630

 286/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.5315 - mae: 1.8833

 312/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.6058 - mae: 1.8951

 348/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.7191 - mae: 1.9111

 382/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8324 - mae: 1.9274

 414/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.9412 - mae: 1.9427

 449/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.0341 - mae: 1.9572

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1218 - mae: 1.9678

 499/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.2581 - mae: 1.9827

 527/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.3947 - mae: 1.9980

 549/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4861 - mae: 2.0084

 568/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5575 - mae: 2.0168

 595/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.6488 - mae: 2.0278

 630/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7506 - mae: 2.0404

 654/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8085 - mae: 2.0477

 676/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8593 - mae: 2.0542

 700/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9085 - mae: 2.0605

 725/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9554 - mae: 2.0670

 751/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9975 - mae: 2.0730

 775/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0282 - mae: 2.0775

 800/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0553 - mae: 2.0817

 824/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0785 - mae: 2.0855

 851/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1019 - mae: 2.0895

 875/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1195 - mae: 2.0926

 901/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1401 - mae: 2.0962

 926/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1612 - mae: 2.0998

 951/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1807 - mae: 2.1031

 978/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2042 - mae: 2.1070

1004/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2233 - mae: 2.1101

1029/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2433 - mae: 2.1132

1053/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2616 - mae: 2.1159

1076/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2785 - mae: 2.1184

1099/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2937 - mae: 2.1208

1125/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3080 - mae: 2.1231

1145/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3176 - mae: 2.1247

1158/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3229 - mae: 2.1257

1179/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3311 - mae: 2.1271

1201/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3390 - mae: 2.1285

1223/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3461 - mae: 2.1297

1258/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3571 - mae: 2.1316

1281/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3661 - mae: 2.1331

1303/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3757 - mae: 2.1346

1326/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3855 - mae: 2.1362

1348/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3954 - mae: 2.1377

1374/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4053 - mae: 2.1392

1411/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4196 - mae: 2.1414

1445/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4302 - mae: 2.1430

1480/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4409 - mae: 2.1448

1523/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4546 - mae: 2.1470

1561/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4658 - mae: 2.1487

1598/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4757 - mae: 2.1502

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4791 - mae: 2.1508

1636/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4834 - mae: 2.1515

1651/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4864 - mae: 2.1520

1672/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4901 - mae: 2.1526

1697/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4938 - mae: 2.1533

1725/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.4975 - mae: 2.1540

1753/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.5007 - mae: 2.1546

1781/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.5036 - mae: 2.1551

1813/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.5080 - mae: 2.1558

1843/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.5124 - mae: 2.1565

1871/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5161 - mae: 2.1572

1885/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5180 - mae: 2.1575

1895/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5191 - mae: 2.1577

1906/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5206 - mae: 2.1579

1940/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5247 - mae: 2.1586

1966/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5275 - mae: 2.1591

1998/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5311 - mae: 2.1597

2026/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5338 - mae: 2.1602

2058/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5359 - mae: 2.1607

2078/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5367 - mae: 2.1609

2099/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5371 - mae: 2.1610

2121/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5370 - mae: 2.1611

2149/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5364 - mae: 2.1612

2172/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5356 - mae: 2.1612

2197/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5346 - mae: 2.1612

2218/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5339 - mae: 2.1612

2241/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5335 - mae: 2.1613

2264/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5332 - mae: 2.1614

2284/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5341 - mae: 2.1616

2307/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5358 - mae: 2.1620

2331/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5377 - mae: 2.1623

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.8029 - mae: 2.2053

Epoch 29/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:29 38ms/step - loss: 86.0546 - mae: 9.2766

  24/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 31.6773 - mae: 3.9454

  45/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 33.2516 - mae: 3.9413

  67/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 31.5624 - mae: 3.7898

  91/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 29.0724 - mae: 3.5985

 106/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 27.6037 - mae: 3.4837

 119/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 26.5270 - mae: 3.4080

 145/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 25.2015 - mae: 3.3083

 180/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 24.1974 - mae: 3.2409

 219/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 23.1871 - mae: 3.1759

 262/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 22.1213 - mae: 3.1035

 292/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 21.4849 - mae: 3.0611

 327/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.8041 - mae: 3.0151

 361/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 20.2173 - mae: 2.9766

 397/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 19.6855 - mae: 2.9418

 433/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 19.2260 - mae: 2.9129

 458/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 18.9215 - mae: 2.8933

 497/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 18.4590 - mae: 2.8613

 526/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 18.1866 - mae: 2.8424

 547/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 18.0063 - mae: 2.8303

 570/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.8146 - mae: 2.8175

 583/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.7077 - mae: 2.8103

 597/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.5918 - mae: 2.8020

 614/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.4514 - mae: 2.7917

 636/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.2780 - mae: 2.7791

 661/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 17.0933 - mae: 2.7658

 687/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.9139 - mae: 2.7534

 710/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.7597 - mae: 2.7429

 736/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.5891 - mae: 2.7311

 760/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.4394 - mae: 2.7210

 784/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.2981 - mae: 2.7116

 806/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.1717 - mae: 2.7030

 829/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 16.0448 - mae: 2.6945

 849/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.9367 - mae: 2.6872

 869/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.8311 - mae: 2.6801

 890/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.7243 - mae: 2.6731

 914/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.6056 - mae: 2.6652

 941/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.4750 - mae: 2.6565

 966/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.3582 - mae: 2.6487

 988/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.2638 - mae: 2.6426

1010/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.1759 - mae: 2.6372

1035/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.0837 - mae: 2.6316

1058/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 15.0010 - mae: 2.6266

1085/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.9061 - mae: 2.6210

1106/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.8336 - mae: 2.6165

1119/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.7895 - mae: 2.6139

1135/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.7373 - mae: 2.6107

1150/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.6894 - mae: 2.6078

1167/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.6361 - mae: 2.6046

1184/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.5833 - mae: 2.6014

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.5461 - mae: 2.5990

1210/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.5028 - mae: 2.5963

1225/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.4567 - mae: 2.5933

1239/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.4151 - mae: 2.5905

1254/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.3739 - mae: 2.5878

1272/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.3258 - mae: 2.5847

1295/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.2663 - mae: 2.5809

1318/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.2092 - mae: 2.5773

1339/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.1577 - mae: 2.5740

1361/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.1034 - mae: 2.5704

1382/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 14.0522 - mae: 2.5669

1405/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 13.9964 - mae: 2.5631

1440/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.9175 - mae: 2.5578

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.8371 - mae: 2.5523

1512/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.7638 - mae: 2.5472

1546/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.6958 - mae: 2.5426

1581/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.6262 - mae: 2.5378

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.5641 - mae: 2.5334

1645/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.5035 - mae: 2.5292

1669/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.4593 - mae: 2.5262

1685/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.4301 - mae: 2.5241

1703/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.3972 - mae: 2.5218

1730/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.3480 - mae: 2.5182

1764/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2861 - mae: 2.5135

1789/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2453 - mae: 2.5103

1814/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.2097 - mae: 2.5074

1837/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1808 - mae: 2.5051

1862/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 13.1495 - mae: 2.5026

1888/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.1170 - mae: 2.5001

1911/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.0882 - mae: 2.4978

1935/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.0588 - mae: 2.4954

1960/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.0294 - mae: 2.4930

1986/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9987 - mae: 2.4905

2010/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9707 - mae: 2.4883

2033/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9438 - mae: 2.4861

2053/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9202 - mae: 2.4842

2070/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.9001 - mae: 2.4825

2083/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8846 - mae: 2.4812

2103/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8609 - mae: 2.4792

2119/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8422 - mae: 2.4776

2149/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.8076 - mae: 2.4746

2185/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7668 - mae: 2.4711

2210/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7391 - mae: 2.4688

2228/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.7193 - mae: 2.4671

2248/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.6976 - mae: 2.4653

2265/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.6791 - mae: 2.4637

2285/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.6576 - mae: 2.4619

2310/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.6309 - mae: 2.4596

2326/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 12.6138 - mae: 2.4582

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 10.1229 - mae: 2.2486

Epoch 30/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:36 41ms/step - loss: 0.3695 - mae: 0.6079

  31/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.0317 - mae: 1.8354

  50/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.7334 - mae: 1.9336

  71/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1534 - mae: 1.9823

  94/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3145 - mae: 2.0029

 117/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3710 - mae: 2.0166

 137/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.4603 - mae: 2.0316

 155/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.5097 - mae: 2.0444

 167/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.5274 - mae: 2.0519

 186/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.5421 - mae: 2.0600

 202/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.5425 - mae: 2.0634

 217/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.5436 - mae: 2.0661

 234/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 7.5572 - mae: 2.0701

 269/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.5930 - mae: 2.0799

 304/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6685 - mae: 2.0936

 340/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.7736 - mae: 2.1098

 375/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.8670 - mae: 2.1239

 402/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.9151 - mae: 2.1314

 427/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.9674 - mae: 2.1392

 460/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0214 - mae: 2.1478

 491/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0731 - mae: 2.1556

 522/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1202 - mae: 2.1626

 542/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1506 - mae: 2.1671

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2031 - mae: 2.1750

 604/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2393 - mae: 2.1807

 616/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2544 - mae: 2.1832

 631/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2731 - mae: 2.1863

 668/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3094 - mae: 2.1924

 701/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3365 - mae: 2.1968

 723/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3557 - mae: 2.1997

 743/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3704 - mae: 2.2021

 763/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3808 - mae: 2.2038

 779/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3897 - mae: 2.2052

 797/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3986 - mae: 2.2068

 817/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4063 - mae: 2.2082

 835/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4121 - mae: 2.2094

 854/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4218 - mae: 2.2108

 874/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4352 - mae: 2.2124

 887/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4426 - mae: 2.2133

 901/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4488 - mae: 2.2140

 914/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4541 - mae: 2.2145

 936/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4624 - mae: 2.2154

 949/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4663 - mae: 2.2158

 962/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4699 - mae: 2.2161

 975/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4727 - mae: 2.2163

 987/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4750 - mae: 2.2164

1004/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4780 - mae: 2.2166

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4811 - mae: 2.2167

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4828 - mae: 2.2167

1064/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4834 - mae: 2.2165

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4827 - mae: 2.2161

1104/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4835 - mae: 2.2157

1123/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4890 - mae: 2.2157

1141/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4944 - mae: 2.2156

1160/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4988 - mae: 2.2155

1184/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5079 - mae: 2.2157

1205/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5168 - mae: 2.2161

1226/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5247 - mae: 2.2164

1245/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5304 - mae: 2.2165

1265/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5349 - mae: 2.2165

1287/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5407 - mae: 2.2165

1308/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5487 - mae: 2.2169

1328/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5584 - mae: 2.2175

1350/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5685 - mae: 2.2182

1370/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5765 - mae: 2.2187

1391/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5845 - mae: 2.2192

1409/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.5922 - mae: 2.2198

1432/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6010 - mae: 2.2204

1452/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6075 - mae: 2.2208

1464/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6110 - mae: 2.2209

1486/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6166 - mae: 2.2212

1516/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6228 - mae: 2.2213

1546/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6272 - mae: 2.2213

1583/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6300 - mae: 2.2208

1620/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6309 - mae: 2.2201

1652/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6307 - mae: 2.2195

1680/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6296 - mae: 2.2188

1710/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6281 - mae: 2.2181

1744/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6250 - mae: 2.2171

1779/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6212 - mae: 2.2160

1819/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6176 - mae: 2.2150

1847/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6166 - mae: 2.2144

1872/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6166 - mae: 2.2140

1889/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6174 - mae: 2.2139

1913/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6191 - mae: 2.2137

1951/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6226 - mae: 2.2135

1980/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6254 - mae: 2.2133

2010/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6278 - mae: 2.2132

2040/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6305 - mae: 2.2130

2079/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6356 - mae: 2.2130

2121/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6399 - mae: 2.2128

2149/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6428 - mae: 2.2128

2170/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6446 - mae: 2.2127

2186/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6457 - mae: 2.2127

2207/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6472 - mae: 2.2126

2232/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6489 - mae: 2.2125

2254/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6505 - mae: 2.2125

2273/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6516 - mae: 2.2124

2298/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6526 - mae: 2.2123

2337/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6543 - mae: 2.2120

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.7609 - mae: 2.2017

Epoch 31/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 54s 23ms/step - loss: 0.1644 - mae: 0.4055

  32/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.1766 - mae: 1.4744

  56/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.0949 - mae: 1.6632

  81/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3845 - mae: 1.7398

 103/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5860 - mae: 1.8055

 125/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6109 - mae: 1.8390

 150/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5839 - mae: 1.8584

 176/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5958 - mae: 1.8716

 203/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5946 - mae: 1.8810

 226/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5879 - mae: 1.8888

 251/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5811 - mae: 1.8971

 278/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5724 - mae: 1.9051

 301/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5510 - mae: 1.9084

 328/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5209 - mae: 1.9123

 353/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5031 - mae: 1.9169

 381/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4879 - mae: 1.9220

 400/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4829 - mae: 1.9254

 422/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4806 - mae: 1.9303

 445/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4840 - mae: 1.9362

 469/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4889 - mae: 1.9414

 492/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4849 - mae: 1.9449

 515/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4805 - mae: 1.9481

 539/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4776 - mae: 1.9513

 564/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4700 - mae: 1.9538

 591/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4604 - mae: 1.9563

 617/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4512 - mae: 1.9585

 641/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4409 - mae: 1.9603

 662/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4318 - mae: 1.9619

 681/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4226 - mae: 1.9631

 703/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4141 - mae: 1.9643

 726/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4129 - mae: 1.9664

 750/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4125 - mae: 1.9686

 771/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4204 - mae: 1.9710

 793/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4413 - mae: 1.9744

 816/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4619 - mae: 1.9779

 839/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4808 - mae: 1.9811

 862/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4990 - mae: 1.9842

 887/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5236 - mae: 1.9877

 912/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5543 - mae: 1.9917

 934/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5792 - mae: 1.9951

 954/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6009 - mae: 1.9981

 977/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6245 - mae: 2.0015

1002/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6491 - mae: 2.0050

1029/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6748 - mae: 2.0088

1053/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.6973 - mae: 2.0120

1077/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7244 - mae: 2.0158

1102/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7554 - mae: 2.0199

1127/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.7835 - mae: 2.0236

1154/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8135 - mae: 2.0276

1175/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8356 - mae: 2.0306

1197/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8560 - mae: 2.0334

1228/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8805 - mae: 2.0367

1262/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9050 - mae: 2.0403

1290/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9243 - mae: 2.0432

1319/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9430 - mae: 2.0460

1355/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9617 - mae: 2.0489

1396/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9806 - mae: 2.0518

1432/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0024 - mae: 2.0547

1477/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0289 - mae: 2.0584

1508/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0447 - mae: 2.0606

1536/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0584 - mae: 2.0626

1555/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0672 - mae: 2.0639

1574/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0762 - mae: 2.0652

1604/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0895 - mae: 2.0671

1644/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1073 - mae: 2.0697

1670/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1179 - mae: 2.0713

1691/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1261 - mae: 2.0725

1715/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1346 - mae: 2.0739

1737/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1416 - mae: 2.0749

1758/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1484 - mae: 2.0760

1780/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1548 - mae: 2.0771

1801/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1602 - mae: 2.0780

1822/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1657 - mae: 2.0789

1844/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1744 - mae: 2.0801

1868/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.1934 - mae: 2.0818

1888/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2110 - mae: 2.0833

1906/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2266 - mae: 2.0846

1929/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2460 - mae: 2.0864

1954/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2657 - mae: 2.0881

1977/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2827 - mae: 2.0896

1999/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.2981 - mae: 2.0909

2021/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3128 - mae: 2.0922

2047/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3298 - mae: 2.0938

2072/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3461 - mae: 2.0953

2099/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3634 - mae: 2.0969

2124/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3784 - mae: 2.0982

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3909 - mae: 2.0994

2165/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4009 - mae: 2.1002

2180/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4084 - mae: 2.1009

2200/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4181 - mae: 2.1018

2222/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4284 - mae: 2.1027

2250/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4411 - mae: 2.1038

2267/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4484 - mae: 2.1045

2298/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4611 - mae: 2.1057

2329/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4736 - mae: 2.1069

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.3983 - mae: 2.1986

Epoch 32/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:25 36ms/step - loss: 2.2088 - mae: 1.4862

  24/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 4.2485 - mae: 1.7343

  50/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.5050 - mae: 1.6871

  73/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.1492 - mae: 1.7638

  97/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.3191 - mae: 1.7718

 118/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.4125 - mae: 1.7770

 141/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.5422 - mae: 1.7956

 167/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.6908 - mae: 1.8214

 191/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.8168 - mae: 1.8450

 217/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 5.9544 - mae: 1.8686

 243/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.0642 - mae: 1.8868

 267/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.1571 - mae: 1.9010

 299/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.2346 - mae: 1.9133

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 6.2828 - mae: 1.9212

 362/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.3111 - mae: 1.9261

 397/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.3526 - mae: 1.9339

 423/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.3809 - mae: 1.9395

 449/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4072 - mae: 1.9446

 467/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4287 - mae: 1.9484

 497/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4761 - mae: 1.9560

 531/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5276 - mae: 1.9630

 542/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5439 - mae: 1.9650

 559/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5673 - mae: 1.9680

 594/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6127 - mae: 1.9736

 634/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6606 - mae: 1.9794

 662/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6847 - mae: 1.9822

 679/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6952 - mae: 1.9834

 701/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7043 - mae: 1.9841

 724/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7123 - mae: 1.9849

 744/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7179 - mae: 1.9854

 758/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7215 - mae: 1.9857

 771/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7236 - mae: 1.9858

 793/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7321 - mae: 1.9863

 816/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7416 - mae: 1.9870

 838/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7478 - mae: 1.9872

 859/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7557 - mae: 1.9874

 880/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7705 - mae: 1.9883

 904/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7868 - mae: 1.9894

 925/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8010 - mae: 1.9903

 948/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8178 - mae: 1.9914

 970/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8351 - mae: 1.9927

 995/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8545 - mae: 1.9941

1019/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8728 - mae: 1.9956

1043/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8894 - mae: 1.9969

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9128 - mae: 1.9990

1098/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9301 - mae: 2.0007

1121/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9461 - mae: 2.0023

1144/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9638 - mae: 2.0040

1169/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9821 - mae: 2.0057

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9996 - mae: 2.0073

1221/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0140 - mae: 2.0086

1248/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0288 - mae: 2.0101

1269/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0389 - mae: 2.0110

1291/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0485 - mae: 2.0119

1326/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0608 - mae: 2.0130

1360/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0704 - mae: 2.0138

1391/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0776 - mae: 2.0143

1414/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0820 - mae: 2.0145

1436/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0866 - mae: 2.0147

1460/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0930 - mae: 2.0151

1484/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0986 - mae: 2.0154

1503/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1031 - mae: 2.0156

1526/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1081 - mae: 2.0158

1556/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1169 - mae: 2.0163

1581/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1263 - mae: 2.0169

1613/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1378 - mae: 2.0176

1642/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1474 - mae: 2.0182

1668/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1558 - mae: 2.0187

1695/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1632 - mae: 2.0191

1724/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1700 - mae: 2.0193

1754/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1761 - mae: 2.0195

1783/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1817 - mae: 2.0197

1809/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1869 - mae: 2.0200

1835/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1925 - mae: 2.0204

1865/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1983 - mae: 2.0208

1892/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2034 - mae: 2.0212

1916/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2077 - mae: 2.0215

1952/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2145 - mae: 2.0221

1986/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2212 - mae: 2.0227

2019/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2278 - mae: 2.0232

2055/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2339 - mae: 2.0237

2088/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2394 - mae: 2.0242

2115/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2442 - mae: 2.0246

2154/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2508 - mae: 2.0251

2186/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2564 - mae: 2.0256

2208/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2601 - mae: 2.0259

2234/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2649 - mae: 2.0263

2249/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2684 - mae: 2.0266

2262/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2714 - mae: 2.0269

2277/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2746 - mae: 2.0272

2294/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2782 - mae: 2.0275

2308/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2812 - mae: 2.0278

2320/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2838 - mae: 2.0281

2339/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2878 - mae: 2.0285

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.8637 - mae: 2.0888

Epoch 33/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:12 31ms/step - loss: 1.5372 - mae: 1.2398

  33/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3.6053 - mae: 1.5471

  61/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1235 - mae: 1.9359

  88/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3187 - mae: 2.0822

 114/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 9.7559 - mae: 2.1457

 145/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.8952 - mae: 2.1779

 172/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.8651 - mae: 2.1869

 197/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.7793 - mae: 2.1880

 226/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6612 - mae: 2.1842

 257/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4921 - mae: 2.1705

 276/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3858 - mae: 2.1613

 303/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2645 - mae: 2.1525

 330/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.1611 - mae: 2.1454

 364/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.0174 - mae: 2.1334

 387/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.9218 - mae: 2.1247

 411/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.8277 - mae: 2.1157

 439/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.7214 - mae: 2.1056

 461/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.6636 - mae: 2.1000

 489/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.6003 - mae: 2.0939

 522/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5415 - mae: 2.0890

 551/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4989 - mae: 2.0859

 578/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4628 - mae: 2.0836

 593/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4511 - mae: 2.0828

 609/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4568 - mae: 2.0830

 623/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4622 - mae: 2.0834

 635/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4664 - mae: 2.0838

 651/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4716 - mae: 2.0845

 668/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4797 - mae: 2.0856

 684/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4912 - mae: 2.0869

 702/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5063 - mae: 2.0886

 731/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5265 - mae: 2.0911

 760/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5487 - mae: 2.0943

 790/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5742 - mae: 2.0980

 814/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5962 - mae: 2.1014

 844/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.6195 - mae: 2.1050

 869/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.6418 - mae: 2.1080

 889/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.6586 - mae: 2.1102

 917/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7143 - mae: 2.1148

 940/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7621 - mae: 2.1187

 968/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8144 - mae: 2.1229

 997/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8643 - mae: 2.1268

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8960 - mae: 2.1294

1039/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9325 - mae: 2.1325

1065/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9716 - mae: 2.1359

1094/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0106 - mae: 2.1395

1137/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0606 - mae: 2.1441

1165/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0864 - mae: 2.1464

1203/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1164 - mae: 2.1491

1239/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1404 - mae: 2.1512

1275/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1628 - mae: 2.1533

1304/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1785 - mae: 2.1549

1342/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.1974 - mae: 2.1568

1381/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2161 - mae: 2.1586

1411/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2285 - mae: 2.1599

1442/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2396 - mae: 2.1611

1478/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2518 - mae: 2.1624

1521/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2651 - mae: 2.1641

1554/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2733 - mae: 2.1651

1582/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2788 - mae: 2.1659

1612/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2847 - mae: 2.1668

1641/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2892 - mae: 2.1675

1670/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2924 - mae: 2.1680

1690/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2953 - mae: 2.1686

1700/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2967 - mae: 2.1688

1708/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2977 - mae: 2.1689

1717/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2986 - mae: 2.1691

1732/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.2996 - mae: 2.1693

1747/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3003 - mae: 2.1695

1760/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3007 - mae: 2.1696

1783/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3013 - mae: 2.1699

1795/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3018 - mae: 2.1701

1806/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3022 - mae: 2.1702

1818/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3034 - mae: 2.1704

1833/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3055 - mae: 2.1707

1848/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3077 - mae: 2.1711

1859/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.3094 - mae: 2.1714

1870/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3111 - mae: 2.1717

1884/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3129 - mae: 2.1720

1905/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3152 - mae: 2.1725

1925/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3168 - mae: 2.1729

1947/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3184 - mae: 2.1734

1977/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3202 - mae: 2.1739

2006/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3213 - mae: 2.1744

2037/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3221 - mae: 2.1749

2067/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3225 - mae: 2.1753

2084/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3229 - mae: 2.1756

2099/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3229 - mae: 2.1758

2121/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3228 - mae: 2.1761

2142/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3228 - mae: 2.1764

2162/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3235 - mae: 2.1768

2188/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3251 - mae: 2.1773

2217/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3295 - mae: 2.1780

2246/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3341 - mae: 2.1787

2273/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3380 - mae: 2.1794

2302/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3424 - mae: 2.1802

2329/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3463 - mae: 2.1809

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 9.5947 - mae: 2.2298

Epoch 34/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 57s 24ms/step - loss: 5.4401 - mae: 2.3324

  32/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 14.3305 - mae: 3.0272

  68/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 16.0901 - mae: 2.8907

  97/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.7967 - mae: 2.8312

 130/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 15.0866 - mae: 2.7512

 161/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 14.4368 - mae: 2.6815

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.8664 - mae: 2.6232

 225/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 13.4050 - mae: 2.5792

 259/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.9559 - mae: 2.5361

 291/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.5777 - mae: 2.5001

 319/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 12.2588 - mae: 2.4685

 346/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.9723 - mae: 2.4403

 380/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.6934 - mae: 2.4116

 409/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.4813 - mae: 2.3893

 440/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.2586 - mae: 2.3649

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 11.0368 - mae: 2.3404

 506/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.8563 - mae: 2.3197

 534/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.7083 - mae: 2.3028

 564/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.5580 - mae: 2.2859

 588/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.4497 - mae: 2.2735

 600/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 10.4019 - mae: 2.2682

 611/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.3606 - mae: 2.2637

 622/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.3223 - mae: 2.2596

 633/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.2854 - mae: 2.2556

 656/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.2138 - mae: 2.2482

 669/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.1788 - mae: 2.2446

 691/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.1247 - mae: 2.2394

 717/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0637 - mae: 2.2334

 749/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.9957 - mae: 2.2270

 782/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.9347 - mae: 2.2218

 818/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8758 - mae: 2.2168

 845/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8415 - mae: 2.2141

 874/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.8063 - mae: 2.2115

 905/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7740 - mae: 2.2095

 933/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7447 - mae: 2.2078

 963/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.7141 - mae: 2.2058

 996/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6814 - mae: 2.2037

1024/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6547 - mae: 2.2020

1050/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6295 - mae: 2.2004

1067/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6138 - mae: 2.1994

1078/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.6037 - mae: 2.1987

1092/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5915 - mae: 2.1980

1103/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5820 - mae: 2.1974

1115/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5716 - mae: 2.1967

1129/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5596 - mae: 2.1960

1141/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5500 - mae: 2.1954

1154/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5402 - mae: 2.1949

1168/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5350 - mae: 2.1946

1181/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5313 - mae: 2.1945

1196/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5276 - mae: 2.1945

1222/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5264 - mae: 2.1949

1251/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5268 - mae: 2.1954

1283/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5303 - mae: 2.1963

1310/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5314 - mae: 2.1969

1339/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5302 - mae: 2.1972

1366/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.5271 - mae: 2.1972

1392/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5227 - mae: 2.1971

1424/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5200 - mae: 2.1970

1453/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5199 - mae: 2.1970

1480/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5206 - mae: 2.1971

1509/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5199 - mae: 2.1971

1536/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5172 - mae: 2.1968

1564/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5125 - mae: 2.1962

1596/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.5056 - mae: 2.1953

1627/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4975 - mae: 2.1944

1657/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4895 - mae: 2.1935

1689/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4792 - mae: 2.1923

1719/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4692 - mae: 2.1912

1750/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4597 - mae: 2.1903

1780/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4499 - mae: 2.1892

1808/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4410 - mae: 2.1884

1839/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 9.4324 - mae: 2.1876

1868/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4241 - mae: 2.1868

1895/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4168 - mae: 2.1862

1924/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4107 - mae: 2.1857

1953/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.4047 - mae: 2.1852

1984/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3975 - mae: 2.1846

2012/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3904 - mae: 2.1840

2040/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3829 - mae: 2.1833

2068/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3752 - mae: 2.1825

2098/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3666 - mae: 2.1817

2128/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3588 - mae: 2.1810

2155/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3517 - mae: 2.1804

2183/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3441 - mae: 2.1796

2214/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3354 - mae: 2.1788

2249/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3261 - mae: 2.1777

2279/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3181 - mae: 2.1768

2309/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3100 - mae: 2.1759

2335/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.3030 - mae: 2.1752

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.6880 - mae: 2.1133

Epoch 35/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 53s 23ms/step - loss: 3.1550 - mae: 1.7762

  37/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 1ms/step - loss: 7.0101 - mae: 2.0423

  68/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.6974 - mae: 2.0523

  97/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8130 - mae: 2.0671

 125/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7377 - mae: 2.0637

 152/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7470 - mae: 2.0763

 177/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8149 - mae: 2.0886

 202/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8832 - mae: 2.1010

 229/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9254 - mae: 2.1091

 254/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9401 - mae: 2.1139

 284/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9132 - mae: 2.1142

 309/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8856 - mae: 2.1136

 335/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9206 - mae: 2.1182

 364/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0171 - mae: 2.1262

 389/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1065 - mae: 2.1348

 412/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1842 - mae: 2.1423

 439/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2473 - mae: 2.1476

 463/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2849 - mae: 2.1504

 489/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3200 - mae: 2.1538

 517/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3510 - mae: 2.1572

 548/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3737 - mae: 2.1590

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3847 - mae: 2.1591

 601/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3973 - mae: 2.1584

 625/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4235 - mae: 2.1593

 655/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4697 - mae: 2.1621

 686/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5224 - mae: 2.1658

 715/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5712 - mae: 2.1698

 740/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6098 - mae: 2.1733

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6474 - mae: 2.1770

 796/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.6809 - mae: 2.1800

 819/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7087 - mae: 2.1823

 834/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7256 - mae: 2.1837

 850/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7415 - mae: 2.1849

 868/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7598 - mae: 2.1865

 891/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7795 - mae: 2.1881

 916/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.7959 - mae: 2.1893

 944/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8105 - mae: 2.1902

 963/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8222 - mae: 2.1911

 983/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8357 - mae: 2.1923

1016/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8546 - mae: 2.1938

1057/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8779 - mae: 2.1958

1084/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8889 - mae: 2.1966

1113/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8975 - mae: 2.1970

1136/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9033 - mae: 2.1972

1160/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9076 - mae: 2.1972

1178/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9105 - mae: 2.1972

1198/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9125 - mae: 2.1971

1220/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9135 - mae: 2.1968

1248/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9147 - mae: 2.1963

1275/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9156 - mae: 2.1958

1303/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9185 - mae: 2.1957

1324/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9200 - mae: 2.1955

1352/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9226 - mae: 2.1954

1380/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9250 - mae: 2.1954

1398/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9264 - mae: 2.1954

1411/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9273 - mae: 2.1954

1424/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9278 - mae: 2.1954

1441/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9286 - mae: 2.1954

1456/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9290 - mae: 2.1953

1471/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9296 - mae: 2.1953

1486/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9301 - mae: 2.1953

1499/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9301 - mae: 2.1952

1512/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9303 - mae: 2.1952

1525/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9305 - mae: 2.1952

1546/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9304 - mae: 2.1952

1576/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9289 - mae: 2.1950

1605/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9270 - mae: 2.1947

1635/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9245 - mae: 2.1944

1665/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9208 - mae: 2.1940

1695/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9158 - mae: 2.1933

1713/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9125 - mae: 2.1929

1732/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9091 - mae: 2.1924

1756/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9044 - mae: 2.1918

1783/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.9006 - mae: 2.1912

1813/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8958 - mae: 2.1906

1837/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8919 - mae: 2.1900

1859/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.8883 - mae: 2.1896

1888/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8848 - mae: 2.1890

1934/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8798 - mae: 2.1883

1961/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8764 - mae: 2.1877

1990/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8722 - mae: 2.1871

2018/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8680 - mae: 2.1865

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8641 - mae: 2.1859

2072/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8612 - mae: 2.1854

2101/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8589 - mae: 2.1850

2130/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8565 - mae: 2.1846

2160/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8535 - mae: 2.1841

2189/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8511 - mae: 2.1837

2217/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8486 - mae: 2.1834

2246/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8458 - mae: 2.1830

2273/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8428 - mae: 2.1826

2303/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8392 - mae: 2.1820

2328/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.8366 - mae: 2.1816

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.6529 - mae: 2.1500

Epoch 36/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:14 32ms/step - loss: 7.4508 - mae: 2.7296

  24/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 3.7921 - mae: 1.5173

  53/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.2137 - mae: 1.3608

  81/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.4995 - mae: 1.3904

 111/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 3.9096 - mae: 1.4534

 138/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 4.1688 - mae: 1.5020

 167/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.3590 - mae: 1.5370

 194/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.4891 - mae: 1.5598

 220/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.5763 - mae: 1.5756

 249/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.6661 - mae: 1.5902

 278/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.7519 - mae: 1.6054

 306/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.8350 - mae: 1.6204

 331/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.8887 - mae: 1.6308

 358/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.9372 - mae: 1.6409

 390/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.9911 - mae: 1.6520

 422/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.0630 - mae: 1.6633

 457/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.1631 - mae: 1.6793

 491/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.2886 - mae: 1.6980

 522/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.3928 - mae: 1.7144

 550/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.4884 - mae: 1.7292

 580/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.5868 - mae: 1.7434

 610/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.6987 - mae: 1.7574

 637/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.7917 - mae: 1.7691

 667/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 5.8932 - mae: 1.7820

 693/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 5.9726 - mae: 1.7921

 714/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.0314 - mae: 1.7996

 740/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.1000 - mae: 1.8086

 768/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.1670 - mae: 1.8175

 813/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.2620 - mae: 1.8304

 862/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.3534 - mae: 1.8427

 898/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.4138 - mae: 1.8508

 929/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.4620 - mae: 1.8572

 959/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5022 - mae: 1.8625

 998/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5497 - mae: 1.8688

1034/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5897 - mae: 1.8741

1064/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6246 - mae: 1.8789

1097/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6594 - mae: 1.8840

1122/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6841 - mae: 1.8876

1151/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.7130 - mae: 1.8918

1181/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7420 - mae: 1.8961

1211/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7703 - mae: 1.9003

1244/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.7973 - mae: 1.9044

1271/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8183 - mae: 1.9076

1298/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8394 - mae: 1.9108

1326/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8599 - mae: 1.9139

1355/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8792 - mae: 1.9168

1380/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.8938 - mae: 1.9190

1403/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9083 - mae: 1.9212

1427/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9229 - mae: 1.9234

1454/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9399 - mae: 1.9259

1474/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9525 - mae: 1.9277

1501/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9690 - mae: 1.9302

1525/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 6.9834 - mae: 1.9324

1553/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0010 - mae: 1.9351

1576/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0154 - mae: 1.9373

1604/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0311 - mae: 1.9397

1631/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0463 - mae: 1.9419

1658/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0620 - mae: 1.9441

1684/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0765 - mae: 1.9462

1710/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.0906 - mae: 1.9482

1732/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1020 - mae: 1.9499

1760/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.1164 - mae: 1.9519

1786/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1304 - mae: 1.9539

1811/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1441 - mae: 1.9558

1839/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1593 - mae: 1.9578

1865/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1741 - mae: 1.9598

1890/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1897 - mae: 1.9617

1918/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2065 - mae: 1.9638

1946/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2231 - mae: 1.9659

1970/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2374 - mae: 1.9677

1978/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2422 - mae: 1.9683

1990/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2494 - mae: 1.9692

2019/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2668 - mae: 1.9713

2052/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.2852 - mae: 1.9736

2081/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3005 - mae: 1.9755

2106/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3130 - mae: 1.9771

2136/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3275 - mae: 1.9789

2166/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3414 - mae: 1.9807

2198/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3551 - mae: 1.9825

2225/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3664 - mae: 1.9840

2256/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3794 - mae: 1.9857

2286/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.3912 - mae: 1.9873

2314/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4015 - mae: 1.9886

2341/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4119 - mae: 1.9900

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.3324 - mae: 2.1086

Epoch 37/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 55s 23ms/step - loss: 0.8600 - mae: 0.9274

  35/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.0013 - mae: 2.2758

  67/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.9389 - mae: 2.3326

  93/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5934 - mae: 2.3494

 122/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.1443 - mae: 2.3765

 157/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.5687 - mae: 2.3929

 190/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.6158 - mae: 2.3855

 219/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.5413 - mae: 2.3706

 247/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.4737 - mae: 2.3611

 274/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.3792 - mae: 2.3501

 299/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.2791 - mae: 2.3387

 320/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.1972 - mae: 2.3288

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 10.0776 - mae: 2.3134

 377/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.9478 - mae: 2.2967

 406/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.8360 - mae: 2.2826

 436/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.7148 - mae: 2.2670

 462/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.6245 - mae: 2.2558

 484/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5621 - mae: 2.2485

 499/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.5233 - mae: 2.2439

 516/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4803 - mae: 2.2389

 537/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4402 - mae: 2.2338

 564/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.4176 - mae: 2.2304

 591/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3982 - mae: 2.2274

 609/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3816 - mae: 2.2251

 634/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3526 - mae: 2.2212

 662/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.3178 - mae: 2.2167

 687/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2944 - mae: 2.2134

 715/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2677 - mae: 2.2099

 748/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2408 - mae: 2.2062

 769/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2249 - mae: 2.2040

 787/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.2102 - mae: 2.2020

 807/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 9.1916 - mae: 2.1995

 834/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1665 - mae: 2.1961

 855/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1482 - mae: 2.1937

 880/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1269 - mae: 2.1908

 906/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.1039 - mae: 2.1878

 925/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0857 - mae: 2.1855

 952/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0632 - mae: 2.1825

 976/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0454 - mae: 2.1801

1004/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0307 - mae: 2.1781

1030/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0197 - mae: 2.1765

1056/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 9.0077 - mae: 2.1748

1075/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9979 - mae: 2.1735

1092/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9903 - mae: 2.1725

1111/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9809 - mae: 2.1712

1132/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9698 - mae: 2.1697

1147/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9614 - mae: 2.1687

1166/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9509 - mae: 2.1674

1183/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9408 - mae: 2.1662

1200/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9300 - mae: 2.1649

1218/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9183 - mae: 2.1635

1236/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.9072 - mae: 2.1622

1262/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8901 - mae: 2.1602

1293/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8687 - mae: 2.1576

1322/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8489 - mae: 2.1551

1350/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8305 - mae: 2.1528

1379/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.8121 - mae: 2.1505

1406/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7965 - mae: 2.1486

1432/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7838 - mae: 2.1471

1463/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7693 - mae: 2.1454

1493/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7554 - mae: 2.1438

1519/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7438 - mae: 2.1425

1542/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7336 - mae: 2.1414

1573/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7197 - mae: 2.1399

1600/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.7077 - mae: 2.1386

1630/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6952 - mae: 2.1372

1653/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6863 - mae: 2.1361

1679/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6762 - mae: 2.1349

1709/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6648 - mae: 2.1336

1733/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6565 - mae: 2.1327

1759/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6479 - mae: 2.1317

1788/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6399 - mae: 2.1309

1811/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6335 - mae: 2.1302

1830/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.6281 - mae: 2.1296

1859/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6197 - mae: 2.1286

1886/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6118 - mae: 2.1278

1914/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.6034 - mae: 2.1268

1935/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5969 - mae: 2.1261

1964/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5882 - mae: 2.1252

2001/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5764 - mae: 2.1239

2048/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5615 - mae: 2.1222

2078/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5522 - mae: 2.1212

2109/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5425 - mae: 2.1202

2148/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5304 - mae: 2.1189

2177/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5208 - mae: 2.1178

2208/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5102 - mae: 2.1166

2236/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.5008 - mae: 2.1155

2264/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4915 - mae: 2.1144

2294/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4822 - mae: 2.1133

2325/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.4728 - mae: 2.1122

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.7906 - mae: 2.0362

Epoch 38/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 59s 25ms/step - loss: 0.6023 - mae: 0.7761

  21/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 10.0957 - mae: 2.6153

  49/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.8889 - mae: 2.4475

  76/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 8.3095 - mae: 2.3546

 103/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.7981 - mae: 2.2551

 132/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5294 - mae: 2.1930

 161/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3384 - mae: 2.1543

 187/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.2231 - mae: 2.1272

 215/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.1283 - mae: 2.1026

 250/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.0050 - mae: 2.0708

 283/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8738 - mae: 2.0408

 321/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.7388 - mae: 2.0114

 354/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6882 - mae: 1.9978

 394/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6510 - mae: 1.9859

 436/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6233 - mae: 1.9769

 473/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6050 - mae: 1.9717

 511/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6141 - mae: 1.9700

 535/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6146 - mae: 1.9686

 552/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6111 - mae: 1.9671

 574/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6042 - mae: 1.9648

 601/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5993 - mae: 1.9627

 625/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5943 - mae: 1.9611

 648/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.5851 - mae: 1.9590

 661/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5807 - mae: 1.9578

 673/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5812 - mae: 1.9571

 683/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5839 - mae: 1.9568

 693/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.5913 - mae: 1.9569

 714/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6104 - mae: 1.9574

 743/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6363 - mae: 1.9584

 773/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.6631 - mae: 1.9599

 801/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.6867 - mae: 1.9614

 829/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.7105 - mae: 1.9631

 856/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.7383 - mae: 1.9656

 884/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.7664 - mae: 1.9682

 910/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.7930 - mae: 1.9707

 939/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8265 - mae: 1.9741

 967/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8589 - mae: 1.9776

1001/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.8963 - mae: 1.9816

1030/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9312 - mae: 1.9851

1065/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9711 - mae: 1.9890

1087/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 6.9970 - mae: 1.9916

1101/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0168 - mae: 1.9934

1140/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.0697 - mae: 1.9983

1168/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1061 - mae: 2.0020

1198/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1405 - mae: 2.0054

1226/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1685 - mae: 2.0081

1246/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.1869 - mae: 2.0098

1270/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.2073 - mae: 2.0116

1299/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2300 - mae: 2.0137

1329/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2515 - mae: 2.0156

1356/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2702 - mae: 2.0173

1386/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.2887 - mae: 2.0189

1413/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3049 - mae: 2.0204

1443/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3215 - mae: 2.0218

1471/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3363 - mae: 2.0232

1501/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3518 - mae: 2.0247

1528/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3644 - mae: 2.0260

1554/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3756 - mae: 2.0270

1580/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3853 - mae: 2.0279

1610/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.3972 - mae: 2.0290

1639/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4086 - mae: 2.0301

1659/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4157 - mae: 2.0308

1683/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4242 - mae: 2.0315

1711/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4336 - mae: 2.0324

1738/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4415 - mae: 2.0331

1764/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4484 - mae: 2.0336

1796/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.4563 - mae: 2.0343

1834/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4653 - mae: 2.0351

1867/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4745 - mae: 2.0359

1901/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4854 - mae: 2.0370

1937/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.4970 - mae: 2.0383

1964/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5056 - mae: 2.0393

1997/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5181 - mae: 2.0407

2033/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5312 - mae: 2.0421

2064/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5413 - mae: 2.0434

2084/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5476 - mae: 2.0441

2110/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5556 - mae: 2.0451

2135/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5626 - mae: 2.0459

2163/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5695 - mae: 2.0467

2192/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5760 - mae: 2.0474

2218/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5816 - mae: 2.0481

2243/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5862 - mae: 2.0486

2269/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5904 - mae: 2.0491

2294/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5942 - mae: 2.0495

2308/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5963 - mae: 2.0498

2323/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5986 - mae: 2.0501

2338/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.6008 - mae: 2.0503

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.9333 - mae: 2.0887

Epoch 39/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 1:20 34ms/step - loss: 3.2095 - mae: 1.7915

  19/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 7.4797 - mae: 2.3841

  33/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.9135 - mae: 2.2650

  48/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.6685 - mae: 2.1972

  65/2350 ━━━━━━━━━━━━━━━━━━━━ 7s 3ms/step - loss: 6.3871 - mae: 2.1308

  86/2350 ━━━━━━━━━━━━━━━━━━━━ 6s 3ms/step - loss: 6.4978 - mae: 2.1199

 117/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 6.7418 - mae: 2.1097

 144/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 3ms/step - loss: 6.9623 - mae: 2.1103

 172/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.1504 - mae: 2.1129

 201/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.2613 - mae: 2.1128

 230/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.3115 - mae: 2.1090

 263/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.4312 - mae: 2.1107

 291/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.5386 - mae: 2.1161

 317/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6122 - mae: 2.1213

 346/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6626 - mae: 2.1239

 373/2350 ━━━━━━━━━━━━━━━━━━━━ 4s 2ms/step - loss: 7.6930 - mae: 2.1254

 401/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7012 - mae: 2.1239

 429/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7037 - mae: 2.1213

 456/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7056 - mae: 2.1194

 484/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.6985 - mae: 2.1162

 510/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7050 - mae: 2.1155

 537/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7107 - mae: 2.1153

 563/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7106 - mae: 2.1148

 595/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7065 - mae: 2.1134

 625/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7242 - mae: 2.1134

 648/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7424 - mae: 2.1144

 673/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7609 - mae: 2.1158

 701/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7796 - mae: 2.1174

 727/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.7989 - mae: 2.1191

 746/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8121 - mae: 2.1203

 766/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8264 - mae: 2.1217

 781/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8355 - mae: 2.1223

 805/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8501 - mae: 2.1236

 831/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8640 - mae: 2.1248

 856/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8724 - mae: 2.1251

 871/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8772 - mae: 2.1252

 882/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8805 - mae: 2.1253

 895/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8836 - mae: 2.1253

 911/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8881 - mae: 2.1254

 935/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.8957 - mae: 2.1257

 954/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9035 - mae: 2.1262

 969/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9089 - mae: 2.1265

 979/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9123 - mae: 2.1267

 989/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9156 - mae: 2.1269

 993/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9168 - mae: 2.1270

1003/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9200 - mae: 2.1272

1026/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9273 - mae: 2.1278

1050/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9331 - mae: 2.1282

1098/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9416 - mae: 2.1286

1124/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9424 - mae: 2.1282

1149/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9406 - mae: 2.1274

1169/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9383 - mae: 2.1266

1194/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9346 - mae: 2.1256

1221/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9303 - mae: 2.1244

1235/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9274 - mae: 2.1237

1246/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9252 - mae: 2.1232

1261/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9217 - mae: 2.1224

1272/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9190 - mae: 2.1218

1296/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9129 - mae: 2.1205

1325/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9075 - mae: 2.1192

1354/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.9040 - mae: 2.1182

1386/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8988 - mae: 2.1169

1406/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8953 - mae: 2.1160

1421/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8928 - mae: 2.1154

1433/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8910 - mae: 2.1150

1451/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8886 - mae: 2.1143

1472/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 7.8855 - mae: 2.1136

1504/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8817 - mae: 2.1126

1535/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8782 - mae: 2.1117

1564/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8766 - mae: 2.1110

1591/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8767 - mae: 2.1106

1620/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8794 - mae: 2.1104

1651/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8848 - mae: 2.1105

1679/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8895 - mae: 2.1106

1703/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8933 - mae: 2.1106

1736/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.8979 - mae: 2.1106

1765/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9022 - mae: 2.1108

1777/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9043 - mae: 2.1109

1792/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9071 - mae: 2.1110

1806/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9103 - mae: 2.1112

1818/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9129 - mae: 2.1114

1834/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9163 - mae: 2.1115

1858/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9214 - mae: 2.1117

1885/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 7.9273 - mae: 2.1120

1911/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9324 - mae: 2.1123

1931/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9359 - mae: 2.1124

1957/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9397 - mae: 2.1125

1983/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9426 - mae: 2.1124

2011/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9452 - mae: 2.1123

2039/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9476 - mae: 2.1122

2067/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9495 - mae: 2.1120

2098/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9515 - mae: 2.1118

2118/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9523 - mae: 2.1116

2133/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9526 - mae: 2.1115

2146/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9528 - mae: 2.1113

2159/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9527 - mae: 2.1111

2176/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9529 - mae: 2.1109

2204/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9536 - mae: 2.1106

2235/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9553 - mae: 2.1104

2265/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9574 - mae: 2.1103

2295/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9601 - mae: 2.1102

2322/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9623 - mae: 2.1101

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9648 - mae: 2.1100

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 8.1584 - mae: 2.1015

Epoch 40/40

   1/2350 ━━━━━━━━━━━━━━━━━━━━ 59s 26ms/step - loss: 0.8371 - mae: 0.9150

  31/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 3.0982 - mae: 1.5187

  61/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.1224 - mae: 1.6540

  94/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 4.9207 - mae: 1.7616

 121/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.3848 - mae: 1.8351

 151/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 5.7280 - mae: 1.8873

 176/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.0321 - mae: 1.9306

 202/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.4210 - mae: 1.9759

 230/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 6.8319 - mae: 2.0199

 257/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.1670 - mae: 2.0575

 284/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.4255 - mae: 2.0851

 299/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.5483 - mae: 2.0982

 319/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.6931 - mae: 2.1136

 347/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 7.9383 - mae: 2.1337

 379/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.1577 - mae: 2.1506

 408/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.2946 - mae: 2.1602

 435/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.3809 - mae: 2.1653

 462/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4404 - mae: 2.1672

 488/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4814 - mae: 2.1674

 513/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5107 - mae: 2.1676

 548/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5375 - mae: 2.1674

 560/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5417 - mae: 2.1667

 575/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5429 - mae: 2.1655

 590/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5402 - mae: 2.1639

 607/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5349 - mae: 2.1619

 634/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5251 - mae: 2.1585

 659/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5207 - mae: 2.1560

 686/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5211 - mae: 2.1540

 713/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5208 - mae: 2.1523

 734/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5215 - mae: 2.1513

 747/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5224 - mae: 2.1508

 758/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5227 - mae: 2.1505

 773/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5227 - mae: 2.1501

 788/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5223 - mae: 2.1496

 803/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5205 - mae: 2.1491

 825/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5157 - mae: 2.1480

 858/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.5058 - mae: 2.1461

 886/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4943 - mae: 2.1441

 913/2350 ━━━━━━━━━━━━━━━━━━━━ 3s 2ms/step - loss: 8.4814 - mae: 2.1419

 942/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4654 - mae: 2.1395

 973/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4453 - mae: 2.1367

 990/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4338 - mae: 2.1351

1004/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4247 - mae: 2.1339

1017/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4161 - mae: 2.1328

1037/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.4025 - mae: 2.1310

1048/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3956 - mae: 2.1301

1066/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3843 - mae: 2.1287

1096/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3647 - mae: 2.1263

1125/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3479 - mae: 2.1241

1153/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3311 - mae: 2.1220

1180/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.3143 - mae: 2.1199

1208/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2976 - mae: 2.1177

1235/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2811 - mae: 2.1155

1263/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2637 - mae: 2.1132

1293/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2456 - mae: 2.1108

1319/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2298 - mae: 2.1087

1348/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.2124 - mae: 2.1065

1377/2350 ━━━━━━━━━━━━━━━━━━━━ 2s 2ms/step - loss: 8.1953 - mae: 2.1045

1407/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1797 - mae: 2.1027

1437/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1651 - mae: 2.1010

1468/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1530 - mae: 2.0994

1497/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1444 - mae: 2.0983

1526/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1365 - mae: 2.0973

1554/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1284 - mae: 2.0963

1574/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1228 - mae: 2.0957

1604/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1146 - mae: 2.0947

1632/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.1072 - mae: 2.0938

1667/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0991 - mae: 2.0929

1694/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0938 - mae: 2.0923

1720/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0883 - mae: 2.0917

1744/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0835 - mae: 2.0912

1770/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0785 - mae: 2.0906

1794/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0736 - mae: 2.0900

1821/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0679 - mae: 2.0893

1845/2350 ━━━━━━━━━━━━━━━━━━━━ 1s 2ms/step - loss: 8.0630 - mae: 2.0887

1872/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0582 - mae: 2.0882

1902/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0527 - mae: 2.0875

1916/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0501 - mae: 2.0872

1938/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0463 - mae: 2.0868

1955/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0439 - mae: 2.0865

1982/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0417 - mae: 2.0863

2003/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0401 - mae: 2.0862

2025/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0388 - mae: 2.0860

2061/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0368 - mae: 2.0858

2095/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0348 - mae: 2.0856

2119/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0339 - mae: 2.0856

2150/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0323 - mae: 2.0854

2178/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0303 - mae: 2.0852

2212/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0272 - mae: 2.0848

2236/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0255 - mae: 2.0846

2270/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0238 - mae: 2.0845

2301/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0222 - mae: 2.0843

2330/2350 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.0202 - mae: 2.0841

2350/2350 ━━━━━━━━━━━━━━━━━━━━ 5s 2ms/step - loss: 7.8746 - mae: 2.0702

In [24]:
# evaluate the model on the test data
res_mse, res_mae = my_model.evaluate(features_test_scaled, labels_test, verbose=0)
print(res_mse, res_mae)

7.555164337158203 2.082695245742798